
import type { Internship, StudentProfile, Company, Application, Notification } from './types';

export const companies: Company[] = [
    {
        id: '1',
        name: 'RELIANCE INDUSTRIES LIMITED',
        logo: 'https://logo.clearbit.com/ril.com',
        website: 'https://www.ril.com',
        description: 'An Indian multinational conglomerate company, headquartered in Mumbai, India. Its diverse businesses include energy, petrochemicals, natural gas, retail, telecommunications, mass media, and textiles.'
    },
    {
        id: '2',
        name: 'TATA CONSULTANCY SERVICES LIMITED',
        logo: 'https://logo.clearbit.com/tcs.com',
        website: 'https://www.tcs.com',
        description: 'An Indian multinational information technology services and consulting company headquartered in Mumbai. It is a part of the Tata Group and operates in 150 locations across 46 countries.'
    },
    {
        id: '3',
        name: 'HDFC BANK LIMITED',
        logo: 'https://logo.clearbit.com/hdfcbank.com',
        website: 'https://www.hdfcbank.com',
        description: 'An Indian banking and financial services company headquartered in Mumbai. It is India\'s largest private sector bank by assets and by market capitalisation as of April 2021.'
    },
    {
        id: '4',
        name: 'OIL AND NATURAL GAS CORPORATION LIMITED',
        logo: 'https://logo.clearbit.com/ongcindia.com',
        website: 'https://www.ongcindia.com',
        description: 'An Indian public sector multinational crude oil and gas company. Its registered office is in New Delhi. It is under the ownership of Ministry of Petroleum and Natural Gas, Government of India.'
    },

    {
        id: '5',
        name: 'INFOSYS LIMITED',
        logo: 'https://logo.clearbit.com/infosys.com',
        website: 'https://www.infosys.com',
        description: 'An Indian multinational information technology company that provides business consulting, information technology and outsourcing services.'
    },
    {
        id: '6',
        name: 'NTPC LIMITED',
        logo: 'https://logo.clearbit.com/ntpc.co.in',
        website: 'https://www.ntpc.co.in',
        description: 'An Indian public sector undertaking, engaged in the business of generation of electricity and allied activities. It is a company incorporated under the Companies Act 1956 and is under the ownership of Ministry of Power, Government of India.'
    },
    {
        id: '7',
        name: 'TATA STEEL LIMITED',
        logo: 'https://logo.clearbit.com/tatasteel.com',
        website: 'https://www.tatasteel.com',
        description: 'An Indian multinational steel-making company, based in Jamshedpur, Jharkhand and headquartered in Mumbai, Maharashtra. It is a part of the Tata Group.'
    },
    {
        id: '8',
        name: 'ITC LIMITED',
        logo: 'https://logo.clearbit.com/itcportal.com',
        website: 'https://www.itcportal.com',
        description: 'An Indian conglomerate with diversified business in FMCG, hotels, software, packaging, paperboards, specialty papers and agri-business.'
    },
    {
        id: '9',
        name: 'INDIAN OIL CORPORATION LIMITED',
        logo: 'https://logo.clearbit.com/iocl.com',
        website: 'https://www.iocl.com',
        description: 'An Indian public sector oil and gas company headquartered in New Delhi. It is the largest commercial oil company in the country, with a net profit of ₹41,653 crore for the financial year 2020-21.'
    },
    {
        id: '10',
        name: 'ICICI BANK LIMITED',
        logo: 'https://logo.clearbit.com/icicibank.com',
        website: 'https://www.icicibank.com',
        description: 'An Indian multinational banking and financial services company with its registered office in Vadodara, Gujarat and corporate office in Mumbai, Maharashtra.'
    },
    {
        id: '11',
        name: 'POWER GRID CORPORATION OF INDIA LIMITED',
        logo: 'https://logo.clearbit.com/powergrid.in',
        website: 'https://www.powergrid.in',
        description: 'An Indian public sector undertaking engaged in transmission of bulk power across different states of India. It is headquartered in Gurugram.'
    },
    {
        id: '12',
        name: 'TATA SONS PRIVATE LIMITED',
        logo: 'https://logo.clearbit.com/tata.com',
        website: 'https://www.tata.com',
        description: 'The holding company of the Tata Group and holds the bulk of shareholding in these companies. It is a private limited company and is based in Mumbai.'
    },
    {
        id: '13',
        name: 'WIPRO LIMITED',
        logo: 'https://logo.clearbit.com/wipro.com',
        website: 'https://www.wipro.com',
        description: 'An Indian multinational corporation that provides information technology, consulting and business process services.'
    },
    {
        id: '14',
        name: 'HCL TECHNOLOGIES LIMITED',
        logo: 'https://logo.clearbit.com/hcltech.com',
        website: 'https://www.hcltech.com',
        description: 'An Indian multinational information technology services and consulting company, headquartered in Noida, Uttar Pradesh, India.'
    },
    {
        id: '15',
        name: 'HINDUSTAN ZINC LIMITED',
        logo: 'https://logo.clearbit.com/hzlindia.com',
        website: 'https://www.hzlindia.com',
        description: 'An Indian integrated mining and resources producer of zinc, lead, silver and cadmium.'
    },
    {
        id: '16',
        name: 'RELIANCE JIO INFOCOMM LIMITED',
        logo: 'https://logo.clearbit.com/jio.com',
        website: 'https://www.jio.com',
        description: 'An Indian telecommunications company and a subsidiary of Jio Platforms, headquartered in Mumbai, Maharashtra, India.'
    },
    {
        id: '17',
        name: 'MAHANADI COALFIELDS LIMITED',
        logo: 'https://logo.clearbit.com/mahanadicoal.in',
        website: 'https://www.mahanadicoal.in',
        description: 'One of the major coal producing companies of India. It is one of the eight subsidiaries of Coal India Limited.'
    },
    {
        id: '18',
        name: 'NMDC LIMITED',
        logo: 'https://logo.clearbit.com/nmdc.co.in',
        website: 'https://www.nmdc.co.in',
        description: 'An Indian public sector undertaking, it is under the ownership of Ministry of Steel, Government of India.'
    },
    {
        id: '19',
        name: 'HINDUSTAN UNILEVER LIMITED',
        logo: 'https://logo.clearbit.com/hul.co.in',
        website: 'https://www.hul.co.in',
        description: 'A British-Dutch manufacturing company headquartered in Mumbai, India. Its products include foods, beverages, cleaning agents, personal care products, water purifiers and consumer goods.'
    },
    {
        id: '20',
        name: 'REC LIMITED',
        logo: 'https://logo.clearbit.com/recindia.nic.in',
        website: 'https://www.recindia.nic.in',
        description: 'A Navratna company under the Ministry of Power, provides financial assistance to state electricity boards, state governments, central/state power utilities, independent power producers, rural electric cooperatives and private sector utilities.'
    },
    {
        id: '21',
        name: 'JSW STEEL LIMITED',
        logo: 'https://logo.clearbit.com/jsw.in',
        website: 'https://www.jsw.in/steel',
        description: 'An Indian multinational steel making company, based in Mumbai, Maharashtra. It is a subsidiary of JSW Group.'
    },
    {
        id: '22',
        name: 'GAIL (INDIA) LIMITED',
        logo: 'https://logo.clearbit.com/gailonline.com',
        website: 'https://www.gailonline.com',
        description: 'The largest state-owned natural gas processing and distribution company in India. It is under the ownership of Ministry of Petroleum and Natural Gas, Government of India.'
    },
    {
        id: '23',
        name: 'COGNIZANT TECHNOLOGY SOLUTIONS INDIA PRIVATE LIMITED',
        logo: 'https://logo.clearbit.com/cognizant.com',
        website: 'https://www.cognizant.com',
        description: 'An American multinational technology company that provides business consulting, information technology and outsourcing services.'
    },
    {
        id: '24',
        name: 'LARSEN AND TOUBRO LIMITED',
        logo: 'https://logo.clearbit.com/larsentoubro.com',
        website: 'https://www.larsentoubro.com',
        description: 'A major Indian multinational engaged in EPC projects, hi-tech manufacturing and services. It operates in over 30 countries worldwide.'
    },
    {
        id: '25',
        name: 'AXIS BANK LIMITED',
        logo: 'https://logo.clearbit.com/axisbank.com',
        website: 'https://www.axisbank.com',
        description: 'An Indian banking and financial services company headquartered in Mumbai, Maharashtra. It sells financial services to large and mid-size companies, SMEs and retail businesses.'
    },
    {
        id: '26',
        name: 'NORTHERN COALFIELDS LIMITED',
        logo: 'https://logo.clearbit.com/nclcil.in',
        website: 'https://www.nclcil.in',
        description: 'A subsidiary of Coal India Limited, which is a government of India undertaking. It is headquartered in Singrauli, Madhya Pradesh.'
    },
    {
        id: '27',
        name: 'OIL INDIA LIMITED',
        logo: 'https://logo.clearbit.com/oil-india.com',
        website: 'https://www.oil-india.com',
        description: 'The second largest hydrocarbon exploration and production Indian public sector company. It is under the ownership of Ministry of Petroleum and Natural Gas, Government of India.'
    },
    {
        id: '28',
        name: 'HINDUSTAN PETROLEUM CORPORATION LIMITED',
        logo: 'https://logo.clearbit.com/hindustanpetroleum.com',
        website: 'https://www.hindustanpetroleum.com',
        description: 'An Indian public sector oil and gas company. It is a subsidiary of ONGC with its headquarters in Mumbai, Maharashtra. It has a 25% market-share in India among public-sector companies.'
    },
    {
        id: '29',
        name: 'JINDAL STEEL & POWER LIMITED',
        logo: 'https://logo.clearbit.com/jindalsteelpower.com',
        website: 'https://www.jindalsteelpower.com',
        description: 'An Indian steel and energy company based in New Delhi. With turnover of approx. ₹40000 crore, JSPL is a part of about ₹130000 crore diversified O.P. Jindal Group conglomerate.'
    },
    {
        id: '30',
        name: 'RELIANCE RETAIL LIMITED',
        logo: 'https://logo.clearbit.com/relianceretail.com',
        website: 'https://www.relianceretail.com',
        description: 'An Indian retail company and a subsidiary of Reliance Industries Limited. Founded in 2006, it is the largest retailer in India in terms of revenue.'
    },
    {
        id: '31',
        name: 'NUCLEAR POWER CORPORATION OF INDIA LIMITED',
        logo: 'https://logo.clearbit.com/npcil.nic.in',
        website: 'https://www.npcil.nic.in',
        description: 'An Indian public sector undertaking based in Mumbai, Maharashtra. It is wholly owned by the Government of India and is responsible for the generation of nuclear power for electricity.'
    },
    {
        id: '32',
        name: 'TECH MAHINDRA LIMITED',
        logo: 'https://logo.clearbit.com/techmahindra.com',
        website: 'https://www.techmahindra.com',
        description: 'An Indian multinational information technology services and consulting company. A part of the Mahindra Group, the company is headquartered in Pune and has its registered office in Mumbai.'
    },
    {
        id: '33',
        name: 'POWER FINANCE CORPORATION LIMITED',
        logo: 'https://logo.clearbit.com/pfcindia.com',
        website: 'https://www.pfcindia.com',
        description: 'An Indian financial institution under the ownership of Ministry of Power, Government of India. Established in 1986, it is the financial back bone of Indian Power Sector.'
    },
    {
        id: '34',
        name: 'ULTRATECH CEMENT LIMITED',
        logo: 'https://logo.clearbit.com/ultratechcement.com',
        website: 'https://www.ultratechcement.com',
        description: 'An Indian cement company based in Mumbai. It is a part of the Aditya Birla Group. UltraTech is the largest manufacturer of grey cement, ready mix concrete and white cement in India.'
    },
    {
        id: '35',
        name: 'INDUSIND BANK LTD.',
        logo: 'https://logo.clearbit.com/indusind.com',
        website: 'https://www.indusind.com',
        description: 'A new-generation Indian bank headquartered in Pune. The bank offers commercial, transactional and electronic banking products and services.'
    },
    {
        id: '36',
        name: 'NHPC LIMITED',
        logo: 'https://logo.clearbit.com/nhpcindia.com',
        website: 'https://www.nhpcindia.com',
        description: 'An Indian government hydropower board under the ownership of Ministry of Power, Government of India that was incorporated in the year 1975 with an authorised capital of ₹2000 million.'
    },
    {
        id: '37',
        name: 'STEEL AUTHORITY OF INDIA LIMITED',
        logo: 'https://logo.clearbit.com/sail.co.in',
        website: 'https://www.sail.co.in',
        description: 'An Indian government-owned steel manufacturing enterprise based in New Delhi, India. It is under the ownership of Ministry of Steel, Government of India.'
    },
    {
        id: '38',
        name: 'MARUTI SUZUKI INDIA LIMITED',
        logo: 'https://logo.clearbit.com/marutisuzuki.com',
        website: 'https://www.marutisuzuki.com',
        description: 'A subsidiary of the Japanese automotive manufacturer Suzuki. It is the largest car manufacturer in India, with a market share of over 43%.'
    },
    {
        id: '39',
        name: 'VEDANTA LIMITED',
        logo: 'https://logo.clearbit.com/vedantalimited.com',
        website: 'https://www.vedantalimited.com',
        description: 'An Indian multinational mining company headquartered in Mumbai, India, with their main operations in iron ore, gold and aluminium mines in Goa, Karnataka, Rajasthan and Odisha.'
    },
    {
        id: '40',
        name: 'BHARAT PETROLEUM CORPORATION LIMITED',
        logo: 'https://logo.clearbit.com/bharatpetroleum.in',
        website: 'https://www.bharatpetroleum.in',
        description: 'An Indian government-owned oil and gas corporation. It is under the ownership of Ministry of Petroleum and Natural Gas, Government of India, headquartered in Mumbai, Maharashtra.'
    }
];

export const internships: Internship[] = [
  {
    id: '1',
    title: 'Embedded Systems Intern',
    company: 'BHARAT PETROLEUM CORPORATION LIMITED',
    description: 'Work on the design and development of embedded systems for defense applications. Gain experience with microcontrollers, FPGAs, and real-time operating systems.',
    longDescription: 'This internship offers a unique opportunity to contribute to national security by working on advanced embedded systems. You will be part of a team of experienced engineers, contributing to live projects and gaining invaluable hands-on experience in a high-tech environment.',
    responsibilities: ['Firmware development for microcontrollers', 'VHDL/Verilog programming for FPGAs', 'Testing and debugging of embedded hardware', 'Documentation of design and development processes'],
    qualifications: ['Pursuing a degree in Electronics and Communication, Electrical Engineering, or a related field', 'Strong programming skills in C/C++', 'Understanding of computer architecture and digital logic design', 'Familiarity with lab equipment like oscilloscopes and logic analyzers'],
    skills: ['C++', 'VHDL', 'Embedded Systems', 'RTOS'],
    domain: 'Engineering',
    location: 'Bangalore',
    image: 'https://picsum.photos/600/400?random=1',
  },
  {
    id: '2',
    title: 'Healthcare Management Intern',
    company: 'RELIANCE RETAIL LIMITED',
    description: 'Assist in hospital administration, patient care coordination, and quality improvement projects. A great opportunity for those interested in healthcare operations.',
    longDescription: 'As a Healthcare Management Intern, you will get a 360-degree view of hospital operations. You will rotate through different departments, from patient services to financial planning, and contribute to projects aimed at improving efficiency and patient satisfaction.',
    responsibilities: ['Shadowing hospital administrators', 'Collecting and analyzing data on patient flow', 'Assisting in the development of patient education materials', 'Participating in quality audits'],
    qualifications: ['Pursuing a degree in Hospital Administration, Public Health, or Business Administration', 'Excellent communication and interpersonal skills', 'Strong analytical and problem-solving abilities', 'A passion for healthcare'],
    skills: ['Healthcare Management', 'Data Analysis', 'Communication'],
    domain: 'Healthcare',
    location: 'Chennai',
    image: 'https://picsum.photos/600/400?random=2',
  },
  {
    id: '3',
    title: 'Civil Engineering Intern',
    company: 'LARSEN AND TOUBRO LIMITED',
    description: 'Join our infrastructure projects and gain hands-on experience in project planning, site supervision, and quality control for large-scale construction projects.',
    longDescription: 'This is a field-based internship where you will be part of a team building the nation\'s infrastructure. You will learn the practical aspects of civil engineering, from reading blueprints to managing resources and ensuring safety compliance on a live construction site.',
    responsibilities: ['Assisting project managers with daily tasks', 'Monitoring construction activities to ensure they meet specifications', 'Conducting quality checks on materials', 'Preparing project progress reports'],
    qualifications: ['Pursuing a degree in Civil Engineering', 'Knowledge of AutoCAD and other civil engineering software', 'Strong understanding of construction materials and methodologies', 'Willingness to work on-site'],
    skills: ['AutoCAD', 'Project Management', 'Quality Control'],
    domain: 'Engineering',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=3',
  },
  {
    id: '4',
    title: 'Fintech Product Intern',
    company: 'HDFC BANK LIMITED',
    description: 'Work on the next generation of digital payment solutions in India. You will be involved in product research, feature definition, and competitor analysis for products like UPI.',
    longDescription: 'Be a part of the digital payments revolution in India. This internship will give you a unique insight into the world of fintech. You will work with product managers to define and launch new features that will be used by millions of people.',
    responsibilities: ['Conducting market and competitor research', 'Writing product requirements documents (PRDs)', 'Collaborating with engineering and design teams', 'Analyzing user data to identify trends and opportunities'],
    qualifications: ['Pursuing a degree in Business, Computer Science, or a related field', 'Strong interest in technology and payments', 'Excellent analytical and communication skills', 'Ability to work in a fast-paced environment'],
    skills: ['Product Management', 'Data Analysis', 'Market Research', 'UPI'],
    domain: 'Finance',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=4',
  },
  {
    id: '5',
    title: 'Agri-Business Intern',
    company: 'ITC LIMITED',
    description: 'Join ITC\'s Agri-Business division and work on projects related to crop sourcing, supply chain management, and rural marketing. An ideal role for agriculture or business students.',
    longDescription: 'This internship provides a deep dive into India\'s agricultural sector. You will work on ITC\'s e-Choupal initiative, interacting with farmers, and contributing to a more efficient and transparent agricultural supply chain. It is a unique blend of fieldwork and corporate strategy.',
    responsibilities: ['Assisting in the procurement of agricultural commodities', 'Analyzing supply chain data to identify inefficiencies', 'Conducting market research in rural areas', 'Supporting the development of farmer training programs'],
    qualifications: ['Pursuing a degree in Agriculture, Agribusiness Management, or a related field', 'Strong analytical skills and proficiency in Excel', 'Good communication skills and willingness to travel to rural areas', 'Understanding of Indian agriculture'],
    skills: ['Supply Chain', 'Market Research', 'Data Analysis'],
    domain: 'Agriculture',
    location: 'Hyderabad',
    image: 'https://picsum.photos/600/400?random=5',
  },
  {
    id: '6',
    title: 'Pharmaceutical Research Intern',
    company: 'HINDUSTAN UNILEVER LIMITED',
    description: 'Work in our R&D labs on drug formulation and development. This is a hands-on role for pharmacy or chemistry students to gain industry experience.',
    longDescription: 'This internship is an excellent opportunity for aspiring scientists to get real-world experience in a leading pharmaceutical company. You will work under the guidance of senior researchers, assisting with experiments, data analysis, and documentation in a state-of-the-art laboratory.',
    responsibilities: ['Assisting with laboratory experiments', 'Preparing chemical solutions and reagents', 'Operating and maintaining lab equipment', 'Recording and analyzing experimental data'],
    qualifications: ['Pursuing a degree in Pharmacy, Chemistry, or a related field', 'Good laboratory skills and understanding of safety protocols', 'Attention to detail and good record-keeping abilities', 'Eagerness to learn about the drug development process'],
    skills: ['Laboratory Skills', 'Chemistry', 'Data Recording'],
    domain: 'Healthcare',
    location: 'Pune',
    image: 'https://picsum.photos/600/400?random=6',
  },
  {
    id: '7',
    title: 'Frontend Developer Intern',
    company: 'TATA CONSULTANCY SERVICES LIMITED',
    description: 'Help build and maintain user interfaces for our flagship payment products. You will work with React, TypeScript, and modern CSS frameworks to create accessible and performant UIs.',
    longDescription: 'As a Frontend Developer Intern, you will be a key member of our product team, translating designs into high-quality code. This role offers a chance to work on applications used by millions, focusing on UI/UX, performance, and accessibility.',
    responsibilities: ['Developing new user-facing features using React.js', 'Building reusable components and front-end libraries for future use', 'Translating designs and wireframes into high-quality code', 'Optimizing components for maximum performance across a vast array of web-capable devices and browsers'],
    qualifications: ['Pursuing a degree in Computer Science or related field', 'Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model', 'Thorough understanding of React.js and its core principles', 'Familiarity with modern front-end build pipelines and tools'],
    skills: ['React', 'TypeScript', 'CSS', 'HTML', 'JavaScript'],
    domain: 'Web Development',
    location: 'Bangalore',
    image: 'https://picsum.photos/600/400?random=7',
  },
  {
    id: '8',
    title: 'Data Science Intern',
    company: 'INFOSYS LIMITED',
    description: 'Apply your data science skills to real healthcare challenges. Work with large datasets to build predictive models and generate insights to improve patient outcomes.',
    longDescription: 'This internship will place you at the intersection of data science and healthcare. You will work with a team of clinicians and data scientists to analyze clinical data, build machine learning models, and contribute to research that can have a real impact on patient care.',
    responsibilities: ['Data cleaning and preprocessing of clinical datasets', 'Building and evaluating machine learning models', 'Visualizing data and communicating findings to stakeholders', 'Collaborating with clinical staff to understand data context'],
    qualifications: ['Pursuing a degree in Computer Science, Statistics, or a related quantitative field', 'Strong programming skills in Python and experience with libraries like Pandas, NumPy, and Scikit-learn', 'Understanding of machine learning algorithms', 'Experience with data visualization tools like Matplotlib or Seaborn'],
    skills: ['Python', 'Machine Learning', 'Pandas', 'Data Visualization'],
    domain: 'Data Science',
    location: 'Hyderabad',
    image: 'https://picsum.photos/600/400?random=8',
  },
  {
    id: '9',
    title: 'UI/UX Design Intern',
    company: 'ITC LIMITED',
    description: 'Join our digital marketing team and help design engaging and intuitive user experiences for our consumer-facing web and mobile applications.',
    longDescription: 'As a UI/UX Design Intern, you will be involved in the entire product development lifecycle, from user research and wireframing to creating high-fidelity mockups and interactive prototypes. This is a great opportunity to build your portfolio with work on major consumer brands.',
    responsibilities: ['Conducting user research and evaluating user feedback', 'Creating user flows, wireframes, prototypes, and mockups', 'Collaborating with product managers and engineers to implement designs', 'Maintaining and evolving our design system'],
    qualifications: ['Pursuing a degree in Design, Human-Computer Interaction, or a related field', 'A portfolio of design projects', 'Proficiency in design tools such as Figma, Sketch, or Adobe XD', 'Understanding of user-centered design principles'],
    skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
    domain: 'Design',
    location: 'Kolkata',
    image: 'https://picsum.photos/600/400?random=9',
  },
  {
    id: '10',
    title: 'Mobile App Development Intern',
    company: 'BHARAT PETROLEUM CORPORATION LIMITED',
    description: 'Develop and enhance secure mobile applications for internal and client use. Work with native or cross-platform frameworks to build robust and efficient apps.',
    longDescription: 'This internship focuses on building secure and reliable mobile applications. You will learn about mobile security best practices and gain experience in developing for both Android and iOS, working on projects that require a high degree of precision and quality.',
    responsibilities: ['Designing and building mobile applications for Android and iOS', 'Collaborating with cross-functional teams to define, design, and ship new features', 'Unit-testing code for robustness, including edge cases, usability, and general reliability', 'Improving application performance'],
    qualifications: ['Pursuing a degree in Computer Science or a related field', 'Experience with mobile development (either native Android/iOS or cross-platform with Flutter/React Native)', 'Strong understanding of mobile UI/UX principles', 'Familiarity with RESTful APIs'],
    skills: ['Android', 'iOS', 'Flutter', 'Java', 'Swift'],
    domain: 'Mobile Development',
    location: 'Ghaziabad',
    image: 'https://picsum.photos/600/400?random=10',
  },
  {
    id: '11',
    title: 'Software Engineer Intern',
    company: 'TATA CONSULTANCY SERVICES LIMITED',
    description: 'Work on enterprise-level software solutions. Gain experience in Java, Spring Boot, and microservices architecture.',
    longDescription: 'This role will immerse you in the world of enterprise software development. You will work with a team of experienced engineers on large-scale projects, learning best practices in coding, testing, and deployment within a corporate environment.',
    responsibilities: ['Develop and maintain Java-based applications', 'Write unit and integration tests', 'Participate in code reviews', 'Collaborate with agile team members'],
    qualifications: ['Pursuing a degree in Computer Science', 'Strong foundation in Java and Object-Oriented Programming', 'Familiarity with Spring framework is a plus', 'Good problem-solving skills'],
    skills: ['Java', 'Spring Boot', 'Microservices', 'SQL'],
    domain: 'Web Development',
    location: 'Pune',
    image: 'https://picsum.photos/600/400?random=11'
  },
  {
    id: '12',
    title: 'Financial Analyst Intern',
    company: 'HDFC BANK LIMITED',
    description: 'Assist in financial planning, analysis, and reporting. This role offers exposure to corporate finance and banking operations.',
    longDescription: 'As a Financial Analyst Intern, you will support our finance team by analyzing financial data, preparing reports, and assisting with budgeting and forecasting. This is a great opportunity to apply your academic knowledge in a real-world financial setting.',
    responsibilities: ['Prepare financial reports and presentations', 'Analyze financial data and create financial models', 'Assist with budgeting and forecasting processes', 'Conduct industry and competitor analysis'],
    qualifications: ['Pursuing a degree in Finance, Accounting, or a related field', 'Strong analytical skills and attention to detail', 'Proficiency in Microsoft Excel', 'Understanding of financial statements'],
    skills: ['Financial Analysis', 'Excel', 'Reporting', 'Accounting'],
    domain: 'Finance',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=12'
  },
  {
    id: '13',
    title: 'Cloud Engineer Intern',
    company: 'WIPRO LIMITED',
    description: 'Work with our cloud infrastructure team. Gain hands-on experience with AWS/Azure, Docker, and Kubernetes.',
    longDescription: 'This internship offers a deep dive into cloud computing. You will help design, build, and maintain our cloud infrastructure, learning about DevOps practices, automation, and container orchestration in a large-scale environment.',
    responsibilities: ['Deploy and manage applications on AWS/Azure', 'Work with Docker and Kubernetes for containerization', 'Automate infrastructure using tools like Terraform', 'Monitor and troubleshoot cloud services'],
    qualifications: ['Pursuing a degree in Computer Science or IT', 'Understanding of cloud computing concepts (IaaS, PaaS, SaaS)', 'Familiarity with Linux/Unix environments', 'Scripting skills in Python or Bash are a plus'],
    skills: ['AWS', 'Azure', 'Docker', 'Kubernetes', 'DevOps'],
    domain: 'Web Development',
    location: 'Bangalore',
    image: 'https://picsum.photos/600/400?random=13'
  },
  {
    id: '14',
    title: 'Human Resources Intern',
    company: 'INFOSYS LIMITED',
    description: 'Support the HR team in recruitment, onboarding, and employee engagement activities. A great opportunity for those interested in a career in HR.',
    longDescription: 'As an HR Intern, you will be involved in various aspects of the employee lifecycle. You will assist with sourcing candidates, coordinating interviews, preparing onboarding materials, and organizing employee engagement events.',
    responsibilities: ['Screen resumes and source candidates', 'Schedule interviews and communicate with candidates', 'Assist with new hire orientation and onboarding', 'Support employee engagement initiatives'],
    qualifications: ['Pursuing a degree in Human Resources, Business, or a related field', 'Excellent communication and interpersonal skills', 'Strong organizational skills', 'Ability to handle confidential information'],
    skills: ['Recruitment', 'Onboarding', 'Communication', 'HR'],
    domain: 'Marketing',
    location: 'Mysore',
    image: 'https://picsum.photos/600/400?random=14'
  },
  {
    id: '15',
    title: 'Mechanical Engineer Intern',
    company: 'TATA STEEL LIMITED',
    description: 'Join our manufacturing plant and gain hands-on experience in process improvement, equipment maintenance, and quality control.',
    longDescription: 'This internship provides practical experience in a heavy manufacturing environment. You will work with our engineering team to optimize production processes, assist with machinery maintenance schedules, and ensure product quality standards are met.',
    responsibilities: ['Analyze production data to identify areas for improvement', 'Assist with the maintenance of mechanical equipment', 'Conduct quality checks on products', 'Prepare technical reports and documentation'],
    qualifications: ['Pursuing a degree in Mechanical Engineering', 'Strong understanding of mechanical principles and materials', 'Familiarity with CAD software like AutoCAD or SolidWorks', 'Willingness to work in a plant environment'],
    skills: ['Mechanical Engineering', 'CAD', 'Quality Control', 'Process Improvement'],
    domain: 'Engineering',
    location: 'Jamshedpur',
    image: 'https://picsum.photos/600/400?random=15'
  },
  {
    id: '16',
    title: 'Marketing Intern',
    company: 'HINDUSTAN UNILEVER LIMITED',
    description: 'Support our brand management teams in developing and executing marketing campaigns for leading consumer brands.',
    longDescription: 'This internship offers a chance to work on some of India\'s most iconic brands. You will assist with market research, campaign development, social media management, and analyzing campaign performance to derive consumer insights.',
    responsibilities: ['Conduct market and competitor research', 'Assist in the creation of marketing materials', 'Manage social media channels for a brand', 'Track and analyze campaign performance'],
    qualifications: ['Pursuing an MBA or a degree in Marketing/Business', 'Strong analytical and communication skills', 'Creative mindset and a passion for brands', 'Familiarity with digital marketing concepts'],
    skills: ['Marketing', 'Brand Management', 'Social Media', 'Market Research'],
    domain: 'Marketing',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=16'
  },
  {
    id: '17',
    title: 'Petroleum Engineering Intern',
    company: 'OIL AND NATURAL GAS CORPORATION LIMITED',
    description: 'Gain field experience in oil and gas exploration and production. Work alongside experienced engineers on drilling and reservoir management projects.',
    longDescription: 'This is a hands-on internship that will take you to the heart of the oil and gas industry. You will get practical exposure to drilling operations, reservoir analysis, and production optimization at one of our active sites.',
    responsibilities: ['Assist with drilling and production operations', 'Collect and analyze geological and reservoir data', 'Prepare technical reports and presentations', 'Adhere to strict safety protocols'],
    qualifications: ['Pursuing a degree in Petroleum, Mechanical, or Chemical Engineering', 'Strong understanding of thermodynamics and fluid mechanics', 'Willingness to work in remote field locations', 'A strong commitment to safety'],
    skills: ['Petroleum Engineering', 'Data Analysis', 'Reservoir Engineering'],
    domain: 'Engineering',
    location: 'Dehradun',
    image: 'https://picsum.photos/600/400?random=17'
  },
  {
    id: '18',
    title: 'Power Systems Intern',
    company: 'NTPC LIMITED',
    description: 'Work in a power plant and learn about power generation, transmission, and distribution. A great role for electrical engineering students.',
    longDescription: 'This internship provides a comprehensive overview of the power sector. You will rotate through different departments in one of our power plants, learning about plant operations, maintenance, and the economics of power generation.',
    responsibilities: ['Assist with the operation and maintenance of power plant equipment', 'Analyze plant performance data', 'Participate in safety drills and procedures', 'Work on a project related to improving plant efficiency'],
    qualifications: ['Pursuing a degree in Electrical Engineering', 'Strong understanding of power systems and electrical machinery', 'Willingness to work in a power plant environment', 'Analytical and problem-solving skills'],
    skills: ['Electrical Engineering', 'Power Systems', 'Data Analysis'],
    domain: 'Engineering',
    location: 'Delhi',
    image: 'https://picsum.photos/600/400?random=18'
  },
  {
    id: '19',
    title: 'Investment Banking Intern',
    company: 'ICICI BANK LIMITED',
    description: 'Support our investment banking team with mergers & acquisitions (M&A), and capital raising transactions. A fast-paced role for finance students.',
    longDescription: 'This internship is a demanding but rewarding experience in the world of investment banking. You will be involved in creating financial models, preparing pitch books, and conducting due diligence for live deals, working closely with senior bankers.',
    responsibilities: ['Build financial models and perform valuation analysis', 'Prepare pitch books and other presentation materials', 'Conduct industry research and due diligence', 'Support deal execution teams'],
    qualifications: ['Pursuing an MBA in Finance or a related degree', 'Strong financial modeling and valuation skills', 'Excellent analytical abilities and attention to detail', 'Ability to work long hours in a high-pressure environment'],
    skills: ['Investment Banking', 'Financial Modeling', 'Valuation', 'Excel'],
    domain: 'Finance',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=19'
  },
  {
    id: '20',
    title: 'Network Engineer Intern',
    company: 'RELIANCE JIO INFOCOMM LIMITED',
    description: 'Work on the design, implementation, and maintenance of our large-scale telecommunications network.',
    longDescription: 'This internship will give you hands-on experience with one of the world\'s largest and most advanced mobile networks. You will learn about network architecture, protocols, and performance optimization, working with cutting-edge technologies.',
    responsibilities: ['Assist with the configuration and maintenance of network devices (routers, switches)', 'Monitor network performance and troubleshoot issues', 'Participate in network design and planning meetings', 'Document network configurations and procedures'],
    qualifications: ['Pursuing a degree in Electronics and Communication or Computer Science', 'Understanding of networking concepts (TCP/IP, routing, switching)', 'Familiarity with Cisco or Juniper equipment is a plus', 'Problem-solving skills'],
    skills: ['Networking', 'Cisco', 'TCP/IP', 'Routing'],
    domain: 'Engineering',
    location: 'Navi Mumbai',
    image: 'https://picsum.photos/600/400?random=20'
  },
   {
    id: '21',
    title: 'Automotive Design Intern',
    company: 'MARUTI SUZUKI INDIA LIMITED',
    description: 'Contribute to the design and development of future vehicle models. Work on CAD modeling, prototyping, and testing of automotive components.',
    longDescription: 'This internship offers an exciting opportunity to be part of the automotive design process. You will work in our R&D center, using CAD software to design components, participating in prototype builds, and assisting with component testing and validation.',
    responsibilities: ['Create 3D models and 2D drawings of automotive parts using CAD software', 'Assist in the development of prototypes', 'Participate in design reviews and brainstorming sessions', 'Conduct testing and analysis of components'],
    qualifications: ['Pursuing a degree in Mechanical or Automotive Engineering', 'Proficiency in CAD software like CATIA or SolidWorks', 'A passion for automobiles and design', 'Creative and problem-solving mindset'],
    skills: ['CAD', 'Automotive Engineering', 'SolidWorks', 'CATIA', 'Design'],
    domain: 'Engineering',
    location: 'Gurgaon',
    image: 'https://picsum.photos/600/400?random=21'
  },
  {
    id: '22',
    title: 'Business Analyst Intern',
    company: 'COGNIZANT TECHNOLOGY SOLUTIONS INDIA PRIVATE LIMITED',
    description: 'Work as a liaison between business stakeholders and technical teams to gather requirements and define software solutions for clients.',
    longDescription: 'As a Business Analyst Intern, you will play a crucial role in our client projects. You will learn how to elicit, analyze, and document business requirements, and then translate them into functional specifications for our development teams.',
    responsibilities: ['Participate in requirement gathering workshops with clients', 'Create business requirement documents (BRDs) and functional specification documents (FSDs)', 'Develop process flow diagrams and use cases', 'Collaborate with developers and testers to ensure requirements are met'],
    qualifications: ['Pursuing an MBA or a degree in Business, IT, or a related field', 'Excellent analytical and communication skills', 'Ability to understand and document complex business processes', 'A bridge between business and technology'],
    skills: ['Business Analysis', 'Requirement Gathering', 'Agile', 'UML'],
    domain: 'Web Development',
    location: 'Chennai',
    image: 'https://picsum.photos/600/400?random=22'
  },
  {
    id: '23',
    title: 'Cybersecurity Intern',
    company: 'HCL TECHNOLOGIES LIMITED',
    description: 'Join our cybersecurity team and assist in monitoring security threats, managing vulnerabilities, and responding to incidents.',
    longDescription: 'This internship provides hands-on experience in the fast-growing field of cybersecurity. You will work in our Security Operations Center (SOC), learning to use security tools to detect, analyze, and respond to cyber threats.',
    responsibilities: ['Monitor security alerts and events using SIEM tools', 'Assist with vulnerability scanning and penetration testing', 'Participate in incident response activities', 'Help develop and update security policies and procedures'],
    qualifications: ['Pursuing a degree in Cybersecurity, Computer Science, or a related field', 'Understanding of cybersecurity principles and concepts', 'Familiarity with security tools (e.g., SIEM, firewalls, IDS/IPS)', 'A strong interest in information security'],
    skills: ['Cybersecurity', 'SIEM', 'Vulnerability Assessment', 'Incident Response'],
    domain: 'Web Development',
    location: 'Noida',
    image: 'https://picsum.photos/600/400?random=23'
  },
  {
    id: '24',
    title: 'AI/ML Engineer Intern',
    company: 'TECH MAHINDRA LIMITED',
    description: 'Develop and deploy machine learning models for various business applications. Work with Python, TensorFlow/PyTorch, and cloud AI platforms.',
    longDescription: 'This internship will allow you to work on cutting-edge AI projects. You will be involved in the entire machine learning lifecycle, from data collection and model training to deployment and monitoring, solving real business problems with AI.',
    responsibilities: ['Collect and preprocess data for machine learning models', 'Train and evaluate models using frameworks like TensorFlow or PyTorch', 'Deploy models to production environments', 'Collaborate with data scientists and software engineers'],
    qualifications: ['Pursuing a Master\'s or PhD in Computer Science, AI, or a related field', 'Strong programming skills in Python', 'Hands-on experience with ML frameworks like TensorFlow, PyTorch, or Scikit-learn', 'Solid understanding of machine learning theory'],
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'PyTorch', 'AI'],
    domain: 'Data Science',
    location: 'Pune',
    image: 'https://picsum.photos/600/400?random=24'
  },
  {
    id: '25',
    title: 'Retail Management Intern',
    company: 'RELIANCE RETAIL LIMITED',
    description: 'Gain experience in retail operations, including store management, inventory control, and customer service in one of our flagship stores.',
    longDescription: 'This internship provides a fast-track introduction to the world of retail. You will learn the fundamentals of store operations, supply chain, merchandising, and customer relationship management in a dynamic and fast-paced environment.',
    responsibilities: ['Assist the store manager with daily operations', 'Manage inventory and stock levels', 'Interact with customers and handle their queries', 'Analyze sales data to identify trends'],
    qualifications: ['Pursuing a degree in Business, Retail Management, or a related field', 'Excellent communication and customer service skills', 'A high level of energy and enthusiasm', 'Willingness to work in a retail store environment'],
    skills: ['Retail', 'Inventory Management', 'Customer Service', 'Sales'],
    domain: 'Marketing',
    location: 'Delhi',
    image: 'https://picsum.photos/600/400?random=25'
  },
   {
    id: '26',
    title: 'Corporate Strategy Intern',
    company: 'TATA SONS PRIVATE LIMITED',
    description: 'Work with the corporate strategy team on projects related to market analysis, long-term planning, and new business initiatives for the Tata Group.',
    longDescription: 'This is a high-profile internship at the heart of one of India\'s largest conglomerates. You will support the strategy team by conducting in-depth research, analyzing industry trends, and preparing presentations for senior leadership on key strategic issues.',
    responsibilities: ['Conduct market, industry, and competitor analysis', 'Assist in the development of strategic plans and business cases', 'Prepare presentations and reports for senior management', 'Support cross-functional projects'],
    qualifications: ['Currently enrolled in a top-tier MBA program', 'Exceptional analytical, problem-solving, and communication skills', 'Strong understanding of business and finance concepts', 'Ability to work independently and handle complex tasks'],
    skills: ['Strategy', 'Market Analysis', 'Corporate Finance', 'Management Consulting'],
    domain: 'Finance',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=26'
  },
  {
    id: '27',
    title: 'Digital Transformation Consultant Intern',
    company: 'TATA CONSULTANCY SERVICES LIMITED',
    description: 'Advise clients on their digital transformation journey. Work on projects involving cloud, data, AI, and IoT to help businesses modernize.',
    longDescription: 'In this role, you will work as part of our consulting practice, helping clients leverage technology to improve their business. You will be involved in client workshops, solution design, and project management for large-scale digital transformation programs.',
    responsibilities: ['Assist in conducting client workshops to understand their needs', 'Help design technology solutions to solve business problems', 'Prepare project proposals and presentations', 'Track project progress and report on key metrics'],
    qualifications: ['Pursuing an MBA or a Master\'s in a technology-related field', 'Strong interest in technology and its business applications', 'Excellent problem-solving and communication skills', 'Ability to work effectively in a team environment'],
    skills: ['Consulting', 'Digital Transformation', 'Cloud Computing', 'AI', 'Project Management'],
    domain: 'Web Development',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=27'
  },
  {
    id: '28',
    title: 'Mining Engineer Intern',
    company: 'HINDUSTAN ZINC LIMITED',
    description: 'Gain practical experience in underground mining operations, including mine planning, ventilation, and safety procedures.',
    longDescription: 'This internship offers a unique opportunity to work in one of India\'s most advanced underground mines. You will get hands-on experience with modern mining technology and learn about the entire mining lifecycle, from planning to extraction.',
    responsibilities: ['Assist with mine planning and design using mining software', 'Monitor ventilation and other environmental factors in the mine', 'Participate in safety audits and meetings', 'Collect and analyze production data'],
    qualifications: ['Pursuing a degree in Mining Engineering', 'Strong understanding of mining principles and practices', 'Familiarity with mining software is a plus', 'A strong commitment to safety and willingness to work underground'],
    skills: ['Mining Engineering', 'Mine Planning', 'Safety Management'],
    domain: 'Engineering',
    location: 'Udaipur',
    image: 'https://picsum.photos/600/400?random=28'
  },
  {
    id: '29',
    title: 'Supply Chain Management Intern',
    company: 'RELIANCE INDUSTRIES LIMITED',
    description: 'Work on optimizing our complex global supply chain. This role involves data analysis, logistics planning, and process improvement.',
    longDescription: 'As a Supply Chain Intern, you will be part of a team managing one of the most complex supply chains in the country. You will use data to identify inefficiencies, help plan logistics, and work on projects to make our supply chain more resilient and cost-effective.',
    responsibilities: ['Analyze supply chain data to identify trends and bottlenecks', 'Assist with logistics and transportation planning', 'Map and document supply chain processes', 'Support process improvement projects'],
    qualifications: ['Pursuing a degree in Supply Chain Management, Industrial Engineering, or a related field', 'Strong analytical skills and proficiency in Excel', 'Understanding of logistics and supply chain principles', 'Problem-solving mindset'],
    skills: ['Supply Chain Management', 'Logistics', 'Data Analysis', 'Process Improvement'],
    domain: 'Engineering',
    location: 'Jamnagar',
    image: 'https://picsum.photos/600/400?random=29'
  },
  {
    id: '30',
    title: 'Quality Assurance Intern',
    company: 'WIPRO LIMITED',
    description: 'Ensure the quality of our software products through manual and automated testing. Learn about testing methodologies and tools.',
    longDescription: 'This internship is a great introduction to the field of software quality assurance. You will learn how to write test cases, execute tests, report bugs, and work with developers to ensure our products meet the highest quality standards.',
    responsibilities: ['Write and execute manual test cases', 'Develop and maintain automated test scripts using Selenium or similar tools', 'Identify, document, and track bugs', 'Participate in agile team meetings'],
    qualifications: ['Pursuing a degree in Computer Science or a related field', 'A keen eye for detail', 'Understanding of the software development lifecycle', 'Familiarity with programming concepts'],
    skills: ['Quality Assurance', 'Manual Testing', 'Automation Testing', 'Selenium', 'JIRA'],
    domain: 'Web Development',
    location: 'Hyderabad',
    image: 'https://picsum.photos/600/400?random=30'
  },
  {
    id: '31',
    title: 'Chemical Engineering Intern',
    company: 'GAIL (INDIA) LIMITED',
    description: 'Work at a natural gas processing plant and gain experience in process control, optimization, and safety management.',
    longDescription: 'This internship offers hands-on experience in the chemical process industry. You will work with experienced engineers to monitor and optimize plant operations, assist with process safety management, and contribute to efficiency improvement projects.',
    responsibilities: ['Monitor and analyze process data', 'Assist with process troubleshooting and optimization', 'Participate in process safety reviews', 'Prepare technical reports and documentation'],
    qualifications: ['Pursuing a degree in Chemical Engineering', 'Strong understanding of chemical engineering principles (thermodynamics, mass transfer, etc.)', 'Familiarity with process simulation software is a plus', 'A strong commitment to safety'],
    skills: ['Chemical Engineering', 'Process Control', 'Safety Management', 'Aspen HYSYS'],
    domain: 'Engineering',
    location: 'Pata',
    image: 'https://picsum.photos/600/400?random=31'
  },
  {
    id: '32',
    title: 'Corporate Communications Intern',
    company: 'AXIS BANK LIMITED',
    description: 'Support the corporate communications team with public relations, internal communications, and social media management.',
    longDescription: 'As a Corporate Communications Intern, you will help shape the bank\'s public image. You will be involved in writing press releases, creating content for internal newsletters, managing our social media presence, and assisting with media relations.',
    responsibilities: ['Draft press releases, articles, and social media posts', 'Assist with the creation of internal communication materials', 'Monitor media coverage of the bank', 'Help organize press conferences and other events'],
    qualifications: ['Pursuing a degree in Communications, Journalism, Public Relations, or a related field', 'Excellent writing and editing skills', 'Strong communication and interpersonal skills', 'Familiarity with social media platforms'],
    skills: ['Corporate Communications', 'Public Relations', 'Content Creation', 'Social Media'],
    domain: 'Marketing',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=32'
  },
  {
    id: '33',
    title: 'Metallurgical Engineer Intern',
    company: 'JINDAL STEEL & POWER LIMITED',
    description: 'Work in our steel plant and gain experience in process metallurgy, quality control, and product development for steel products.',
    longDescription: 'This internship provides practical experience in the steel industry. You will work with our metallurgy team to monitor and improve the steelmaking process, conduct quality tests on products, and assist with the development of new steel grades.',
    responsibilities: ['Analyze metallurgical data to optimize processes', 'Conduct tests on material properties (e.g., hardness, tensile strength)', 'Assist with failure analysis of components', 'Prepare technical reports'],
    qualifications: ['Pursuing a degree in Metallurgical or Materials Engineering', 'Strong understanding of physical and mechanical metallurgy', 'Familiarity with metallurgical testing equipment', 'Willingness to work in a plant environment'],
    skills: ['Metallurgy', 'Materials Science', 'Quality Control', 'Steel'],
    domain: 'Engineering',
    location: 'Raigarh',
    image: 'https://picsum.photos/600/400?random=33'
  },
  {
    id: '34',
    title: 'Nuclear Engineering Intern',
    company: 'NUCLEAR POWER CORPORATION OF INDIA LIMITED',
    description: 'Learn about the operation and safety of nuclear power plants. A unique opportunity for students interested in nuclear energy.',
    longDescription: 'This internship offers a rare glimpse into the world of nuclear power generation. You will receive training on nuclear reactor principles, safety systems, and plant operations, working under the strict supervision of experienced nuclear engineers.',
    responsibilities: ['Attend training sessions on nuclear engineering and safety', 'Assist with the monitoring of plant parameters', 'Participate in safety drills and simulations', 'Work on a research project related to nuclear power'],
    qualifications: ['Pursuing a degree in Nuclear, Mechanical, or Electrical Engineering', 'Excellent academic record and a strong foundation in physics and mathematics', 'A deep commitment to safety and procedure', 'Must pass a rigorous background check'],
    skills: ['Nuclear Engineering', 'Safety Analysis', 'Reactor Physics'],
    domain: 'Engineering',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=34'
  },
  {
    id: '35',
    title: 'Data Analyst Intern',
    company: 'HDFC BANK LIMITED',
    description: 'Analyze large datasets to extract actionable insights for our retail banking division. Work with SQL, Python, and data visualization tools.',
    longDescription: 'As a Data Analyst Intern, you will help us understand our customers better by analyzing transaction data, customer behavior, and market trends. Your insights will help shape our product and marketing strategies.',
    responsibilities: ['Write SQL queries to extract and manipulate data', 'Use Python (Pandas) to clean and analyze data', 'Create dashboards and visualizations using tools like Tableau or Power BI', 'Present findings to business stakeholders'],
    qualifications: ['Pursuing a degree in a quantitative field like Statistics, Economics, or Computer Science', 'Strong SQL skills', 'Proficiency in Python for data analysis', 'Experience with a data visualization tool is a plus'],
    skills: ['SQL', 'Python', 'Pandas', 'Tableau', 'Data Analysis'],
    domain: 'Data Science',
    location: 'Bangalore',
    image: 'https://picsum.photos/600/400?random=35'
  },
  {
    id: '36',
    title: 'Project Finance Intern',
    company: 'POWER FINANCE CORPORATION LIMITED',
    description: 'Assist in the appraisal and financing of large-scale power projects. Learn about project finance, risk analysis, and loan syndication.',
    longDescription: 'This internship offers a unique opportunity to work on financing the nation\'s power infrastructure. You will be involved in appraising project proposals, conducting financial modeling and risk analysis, and preparing documents for loan disbursement.',
    responsibilities: ['Assist in the financial appraisal of power projects', 'Build and maintain project finance models', 'Conduct risk analysis and due diligence', 'Prepare credit appraisal notes'],
    qualifications: ['Pursuing an MBA in Finance or a CA/CFA qualification', 'Strong financial modeling and analysis skills', 'Understanding of project finance concepts', 'Excellent quantitative abilities'],
    skills: ['Project Finance', 'Financial Modeling', 'Risk Analysis', 'Credit Appraisal'],
    domain: 'Finance',
    location: 'New Delhi',
    image: 'https://picsum.photos/600/400?random=36'
  },
  {
    id: '37',
    title: 'Operations Management Intern',
    company: 'ULTRATECH CEMENT LIMITED',
    description: 'Work at one of our cement plants and learn about production planning, logistics, and plant operations management.',
    longDescription: 'This internship provides hands-on experience in managing a large-scale manufacturing operation. You will learn about production scheduling, supply chain management, quality control, and the key performance indicators that drive a successful plant.',
    responsibilities: ['Assist with production planning and scheduling', 'Track and analyze key performance indicators (KPIs)', 'Work on projects to improve operational efficiency', 'Coordinate with logistics and sales teams'],
    qualifications: ['Pursuing a degree in Mechanical, Industrial, or Production Engineering, or an MBA in Operations', 'Strong analytical and problem-solving skills', 'Proficiency in Microsoft Excel', 'Willingness to work in a plant environment'],
    skills: ['Operations Management', 'Production Planning', 'Logistics', 'Process Improvement'],
    domain: 'Engineering',
    location: 'Mumbai',
    image: 'https://picsum.photos/600/400?random=37'
  },
  {
    id: '38',
    title: 'Credit Risk Analyst Intern',
    company: 'INDUSIND BANK LTD.',
    description: 'Assist our credit risk team in evaluating the creditworthiness of corporate borrowers. Involves financial statement analysis and industry research.',
    longDescription: 'As a Credit Risk Analyst Intern, you will learn how to assess the risk of lending to businesses. You will analyze financial statements, conduct industry research, and prepare credit reports to help our team make informed lending decisions.',
    responsibilities: ['Analyze financial statements of companies', 'Conduct industry and economic research', 'Prepare credit appraisal reports', 'Monitor the financial health of existing borrowers'],
    qualifications: ['Pursuing an MBA in Finance, a CA, or a related qualification', 'Strong financial analysis skills', 'Understanding of accounting principles and financial ratios', 'Excellent analytical and writing skills'],
    skills: ['Credit Risk', 'Financial Analysis', 'Accounting', 'Risk Management'],
    domain: 'Finance',
    location: 'Pune',
    image: 'https://picsum.photos/600/400?random=38'
  },
  {
    id: '39',
    title: 'Hydropower Engineering Intern',
    company: 'NHPC LIMITED',
    description: 'Gain experience in the design, construction, and operation of hydropower projects. A great opportunity for civil and electrical engineering students.',
    longDescription: 'This internship offers a chance to work on clean energy projects that are vital for the country. You will be involved in various aspects of hydropower, from site investigation and design to project management and plant operation.',
    responsibilities: ['Assist with the design of hydropower components', 'Monitor construction activities at project sites', 'Collect and analyze hydrological data', 'Prepare technical reports and drawings'],
    qualifications: ['Pursuing a degree in Civil, Electrical, or Mechanical Engineering', 'Interest in renewable energy and hydropower', 'Strong analytical and technical skills', 'Willingness to work in remote project locations'],
    skills: ['Hydropower', 'Civil Engineering', 'Project Management', 'AutoCAD'],
    domain: 'Engineering',
    location: 'Faridabad',
    image: 'https://picsum.photos/600/400?random=39'
  },
  {
    id: '40',
    title: 'Process Safety Intern',
    company: 'BHARAT PETROLEUM CORPORATION LIMITED',
    description: 'Work at our refinery and assist the process safety team in conducting hazard analyses, safety audits, and incident investigations.',
    longDescription: 'This internship focuses on ensuring the safe operation of our refinery. You will learn about process safety management (PSM) principles, participate in hazard and operability (HAZOP) studies, and help implement safety improvement initiatives.',
    responsibilities: ['Participate in safety audits and inspections', 'Assist with hazard identification and risk assessment (HIRA)', 'Help investigate minor incidents and near misses', 'Promote a culture of safety among employees'],
    qualifications: ['Pursuing a degree in Chemical Engineering or a related field', 'A strong commitment to safety and a meticulous nature', 'Understanding of chemical process safety concepts', 'Good communication skills'],
    skills: ['Process Safety', 'Risk Assessment', 'Chemical Engineering', 'HAZOP'],
    domain: 'Engineering',
    location: 'Kochi',
    image: 'https://picsum.photos/600/400?random=40'
  }
];


export const studentProfiles: StudentProfile[] = [
  {
    personalInfo: {
      name: 'Priya Sharma',
      age: 22,
      email: 'priya.sharma@example.com',
      location: 'Mumbai',
      linkedin: 'https://linkedin.com/in/priya-sharma-example',
      university: 'Indian Institute of Technology Bombay',
    },
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'Pandas'],
    preferences: {
      domain: 'Data Science',
      internshipType: 'Full-time',
    },
    resumeSummary: 'A highly motivated data science enthusiast with experience in building machine learning models for classification and regression tasks. Eager to apply my skills to solve real-world problems.',
    eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 600000,
      hasNoGovtJobFamily: true,
      experienceMonths: 12,
    },
  },
  {
    personalInfo: {
      name: 'Rohan Verma',
      age: 21,
      email: 'rohan.verma@example.com',
      location: 'Remote',
      linkedin: 'https://linkedin.com/in/rohan-verma-example',
      university: 'Delhi Technological University',
    },
    skills: ['React', 'TypeScript', 'Node.js', 'Tailwind CSS'],
    preferences: {
      domain: 'Web Development',
      internshipType: 'Remote',
    },
    resumeSummary: 'A passionate full-stack developer with a strong foundation in the MERN stack. I enjoy building responsive and user-friendly web applications.',
    eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 750000,
      hasNoGovtJobFamily: true,
      experienceMonths: 14,
    },
  },
  {
    personalInfo: {
      name: 'Anika Singh',
      age: 23,
      email: 'anika.singh@example.com',
      location: 'Bangalore',
      linkedin: 'https://linkedin.com/in/anika-singh-example',
      university: 'National Institute of Design',
    },
    skills: ['Figma', 'UI Design', 'UX Research', 'Adobe XD'],
    preferences: {
      domain: 'Design',
      internshipType: 'Full-time',
    },
    resumeSummary: 'A creative UX/UI designer with a keen eye for detail and a user-centered approach. Skilled in creating wireframes, prototypes, and high-fidelity mockups.',
    eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 500000,
      hasNoGovtJobFamily: true,
      experienceMonths: 18,
    },
  },
  {
    personalInfo: {
        name: 'Arjun Reddy',
        age: 24,
        email: 'arjun.reddy@example.com',
        location: 'Pune',
        linkedin: 'https://linkedin.com/in/arjun-reddy-example',
        university: 'Vellore Institute of Technology',
    },
    skills: ['Flutter', 'Dart', 'Firebase', 'GetX'],
    preferences: {
        domain: 'Mobile Development',
        internshipType: 'Full-time',
    },
    resumeSummary: 'A skilled Flutter developer with experience in building and publishing mobile apps on both Android and iOS. Proficient in state management and integrating REST APIs.',
    eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 700000,
      hasNoGovtJobFamily: true,
      experienceMonths: 24,
    },
  },
   {
    personalInfo: {
      name: 'Sneha Gupta',
      age: 22,
      email: 'sneha.gupta@example.com',
      location: 'Delhi',
      linkedin: 'https://linkedin.com/in/sneha-gupta-example',
      university: 'Shri Ram College of Commerce',
    },
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Accounting'],
    preferences: {
      domain: 'Finance',
      internshipType: 'Full-time',
    },
    resumeSummary: 'Detail-oriented finance student with a strong understanding of financial principles and a knack for quantitative analysis. Seeking to apply my knowledge in a corporate finance setting.',
    eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 780000,
      hasNoGovtJobFamily: false,
      experienceMonths: 15,
    },
  },
  {
    personalInfo: {
      name: 'Vikram Singh',
      age: 23,
      email: 'vikram.singh@example.com',
      location: 'Pune',
      linkedin: 'https://linkedin.com/in/vikram-singh-example',
      university: 'Symbiosis Centre for Media & Communication',
    },
    skills: ['SEO', 'Content Marketing', 'Google Analytics', 'Social Media'],
    preferences: {
      domain: 'Marketing',
      internshipType: 'Remote',
    },
    resumeSummary: 'A results-driven marketing student with experience in creating and executing digital marketing campaigns. Proven ability to increase brand awareness and engagement.',
     eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 450000,
      hasNoGovtJobFamily: true,
      experienceMonths: 13,
    },
  },
  {
    personalInfo: {
      name: 'Pooja Desai',
      age: 22,
      email: 'pooja.desai@example.com',
      location: 'Mumbai',
      linkedin: 'https://linkedin.com/in/pooja-desai-example',
      university: 'Veermata Jijabai Technological Institute',
    },
    skills: ['AutoCAD', 'Structural Analysis', 'STAAD Pro', 'Project Management'],
    preferences: {
      domain: 'Engineering',
      internshipType: 'Full-time',
    },
    resumeSummary: 'A dedicated civil engineering student with a strong grasp of structural design principles and project management. Eager to contribute to challenging infrastructure projects.',
     eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 650000,
      hasNoGovtJobFamily: true,
      experienceMonths: 20,
    },
  },
  {
    personalInfo: {
      name: 'Rajesh Kumar',
      age: 21,
      email: 'rajesh.kumar@example.com',
      location: 'Hyderabad',
      linkedin: 'https://linkedin.com/in/rajesh-kumar-example',
      university: 'Acharya N.G. Ranga Agricultural University',
    },
    skills: ['Agronomy', 'Supply Chain Management', 'Rural Marketing', 'Data Collection'],
    preferences: {
      domain: 'Agriculture',
      internshipType: 'Full-time',
    },
    resumeSummary: 'An agriculture student passionate about sustainable farming and improving agricultural supply chains. Experienced in fieldwork and engaging with farming communities.',
     eligibility: {
      isNotEmployedFullTime: true,
      isNotEnrolledFullTime: true,
      familyIncome: 300000,
      hasNoGovtJobFamily: true,
      experienceMonths: 16,
    },
  },
];
