
export const universities: string[] = [
    "Acharya N.G. Ranga Agricultural University",
    "Acharya Nagarjuna University",
    "Adikavi Nannaya University",
    "Al-Karim University",
    "Alagappa University",
    "Aliah University",
    "Alipurduar University",
    "Al-Falah University",
    "Aligarh Muslim University",
    "Alliance University",
    "Amity University",
    "Amrita Vishwa Vidyapeetham",
    "Anand Agricultural Univerisity",
    "Anant National University",
    "Andhra Kesari University",
    "Andhra University",
    "Anika Singh",
    "Anna University",
    "Annamalai University",
    "Anurag University",
    "Apeejay Stya University",
    "Apex Professional University",
    "Apex University",
    "A.P.G. (Alakh Prakash Goyal) Shimla University",
    "A.P.J. Abdul Kalam Technological University",
    "Arjun Reddy",
    "ARKA Jain University",
    "ArniUniversity",
    "Arunachal Pradesh University",
    "Arunachal University of Studies",
    "Arunodaya University",
    "Aryabhatta knowledge University",
    "Ashoka University",
    "Asian International University",
    "ASBM University",
    "Assam Agricultural University",
    "Assam Don Bosco University",
    "Assam Down Town University",
    "Assam Rajiv Gandhi University of Co-operative Management",
    "Assam Science & Technology University",
    "Assam University",
    "Assam Women’s University",
    "Atal Bihari Vajpai Hindi Vishwavidyalaya",
    "Atal Bihari Vajpayee Medical University",
    "Atal Bihari Vajpayee Vishwavidyalaya",
    "Atal Medical and Research University",
    "Atmiya University",
    "ATLAS SKILLTECH UNIVERSITY",
    "Atria University",
    "AURO University of Hospitality and Management",
    "Aurora Higher Education & Research Academy",
    "Avantika University",
    "Avinashilingam Institute for Home Science & Higher Education for Women",
    "Awadesh Pratap Singh University",
    "Ayush and Health Sciences University of Chhattisgarh",
    "Azim Premji University",
    "Baba Farid University of Health Sciences",
    "Baba Ghulam Shah Badshah University",
    "Baba Mast Nath University",
    "Babasaheb Bhimrao Ambedkar Bihar University",
    "Babasaheb Bhimrao Ambedkar University",
    "Babu Banarasi Das University",
    "Baddi University of Emerging Sciences & Technology",
    "Bahra University",
    "Banasthali Vidyapith",
    "Banda University of Agriculture & Technology",
    "Bangalore University",
    "Bankura University",
    "Bareilly International University",
    "Barkatullah University",
    "Bengaluru City University",
    "Bengaluru Dr. B.R. Ambedkar School of Economics University",
    "Bengaluru North University",
    "Bennett University",
    "Berhampur University",
    "Bhabha University",
    "Bhagat Phool Singh Mahila Vishwavidyalaya",
    "Bhagwant Global University",
    "Bhagwant University",
    "Bhaikaka University",
    "Bhakta Kavi Narsinh Mehta University",
    "Bharathiar University",
    "Bharathidasan University",
    "Bharath Institute of Higher Education & Research",
    "Bharati Vidyapeeth",
    "Bhartiya Skill Development University",
    "Bharti Vishwavidyalaya",
    "Bhatkhande Music Institute",
    "Bhattadev University",
    "Bhupal Nobles University",
    "Bhupendra Narayan Mandal University",
    "Bidhan Chandra Krishi Vishwavidyalaya",
    "Bihar Agricultural University",
    "Bihar Animal Sciences University",
    "Biju Patnaik University of Technology",
    "Bikaner Technical University",
    "Binod Bihar Mahto Koylanchal University",
    "Birangana Sati Sadhani Rajyik Vishwavidyalaya",
    "Birla Global University",
    "Birla Institute of Technology",
    "Birla Institute of Technology & Science",
    "Birsa Agricultural University",
    "Birsa Munda Tribal University",
    "Bir Tikendrajit University",
    "Biswa Bangla Biswabidyalay",
    "B.L.D.E. Bijapur",
    "BML Munjal University",
    "Bodoland University",
    "Brainware University",
    "B.S. Abdur Rahman Crescent Institute of Science and Technology",
    "Bundelkhand University",
    "Capital University",
    "Career Point University",
    "Central Agricultural University",
    "Central Institute of Buddhist Studies",
    "Central Institute of Fisheries Education",
    "Central Institute of Higher Tibetan Studies",
    "Central Institute of Technology (CIT)",
    "Central Sanskrit University",
    "Central Tribal University of Andhra Pradesh",
    "Central University of Andhra Pradesh",
    "Central University of Gujarat",
    "Central University of Haryana",
    "Central University of Himachal Pradesh",
    "Central University of Jammu",
    "Central University of Jharkhand",
    "Central University of Karnataka",
    "Central University of Kashmir",
    "Central University of Kerala",
    "Central University of Odisha",
    "Central University of Punjab",
    "Central University of Rajasthan",
    "Central University of South Bihar",
    "Central University of Tamil Nadu",
    "Centre for Environmental Planning and Technology University",
    "Centurion University of Technology and Management",
    "Chaitanya",
    "Chanakya National Law University",
    "Chanakya University",
    "Chandigarh University",
    "Chandra Shekhar Azad University of Agriculture & Technology",
    "Charotar University of Science & Technology",
    "Chhatrapati Shivaji Maharaj University",
    "Chhatrapati Shahu Ji Maharaj University",
    "Chhattisgarh Kamdhenu Vishwavidyalaya",
    "Chhattisgarh Swami Vivekanand Technical University",
    "Chennai Mathematical Institute",
    "Chettinad Academy of Research and Education (CARE)",
    "Children’s University",
    "Chinmaya Vishwavidyapeeth",
    "Chitkara University",
    "Choudhary Charan Singh Haryana Agricultural University",
    "Choudhary Charan Singh University",
    "Christ",
    "Cochin University of Science & Technology",
    "Cooch Behar Panchanan Barma University",
    "Cotton Univeristy",
    "Cluster University",
    "Cluster University of Jammu",
    "Cluster University of Srinagar",
    "CMJ University",
    "CMR University",
    "C.T. University",
    "C.U. Shah University",
    "Dakshin Dinajpur University",
    "Damodaram Sanjivayya National Law University",
    "Darshan University",
    "Datta Meghe Institute of Higher Education & Research",
    "Davangere University",
    "D.A.V. University",
    "Dayalbagh Educational Institute",
    "Dayananda Sagar University",
    "Deccan College of Post-Graduate & Research Institute",
    "Deen Bandhu Chhotu Ram University of Science & Technology",
    "Deen Dayal Upadhyay Gorakhpur University",
    "Defence Institute of Advanced Technology",
    "Delhi Pharmaceutical Sciences & Research University",
    "Delhi Skill and Entrepreneurship University",
    "Delhi Sports University",
    "Delhi Teachers University",
    "Delhi Technological University",
    "Desh Bhagat University",
    "Dev Bhoomi Uttrakhand University",
    "Devi Ahilya Vishwavidyalaya",
    "Dev Sanskriti Vishwavidyalaya",
    "Dhanalakshmi Srinivasan University",
    "Dhanamanjuri University",
    "Dharmsinh Desai University",
    "Dharmashastra National Law University",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "Diamond Harbour Women’s University",
    "Dibrugarh University",
    "DIT University",
    "Doon University",
    "Dr. A.P.J. Abdul Kalam Technical University",
    "Dr. A.P.J. Abdul Kalam University",
    "Dr. B.R. Ambedkar National Law University",
    "Dr. B.R. Ambedkar Open University",
    "Dr. B.R. Ambedkar University",
    "Dr. B.R. Ambedkar University of Social Sciences",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Dr. Babasaheb Ambedkar Technological University",
    "Dr. Bhimrao Ambedkar Law University",
    "Dr. C.V. Raman Global University",
    "Dr. C.V. Raman University",
    "Dr. D.Y. Patil Vidyapeeth",
    "Dr. Homi Bhabha State University",
    "Dr. M.G.R. Educational and Research Institute",
    "Dr. N.T.R. University of Health Sciences",
    "Dr. Punjabrao Deshmukh Krishi Vidyapeeth",
    "Dr. Ram Manohar Lohia Awadh University",
    "Dr. Ram Manohar Lohia Institute of Medical Sciences",
    "Dr. Ram Manohar Lohiya National Law University",
    "Dr. Shakuntala Misra National Rehabilitation University",
    "Dr. Shyama Prasad Mukherjee University",
    "Dr. Subhash University",
    "Dr. Vishwanath Karad MIT World Peace University",
    "Dr. Y.S. Parmar University of Horticulture & Forestry",
    "Dr. Y.S.R. Horticultural University",
    "Dr. Y.S.R Architecture and Fine Arts University",
    "Dravidian University",
    "Drs. Kiran & Pallavi Patel Global University (KPGU)",
    "Durg Vishwavidyalaya",
    "D.Y. Patil Agriculture and Technical University",
    "D.Y. Patil Educational Society",
    "D.Y. Patil International University",
    "Eklavya University",
    "Era University",
    "Eternal University",
    "Fakir Mohan University",
    "Flame University",
    "Forest Research Institute",
    "F.S. University",
    "Galgotias University",
    "Gandhigram Rural Institute",
    "Gandhi Institute of Engineering & Technology University",
    "Gandhi Institute of Technology and Management (GITAM)",
    "Gandhinagar University",
    "Gangadhar Meher University",
    "Ganpat University",
    "Garden City University",
    "Gati Shakti Vishwavidyalaya",
    "Gauhati University",
    "Gautam Buddha University",
    "G.B. Pant University of Agriculture and Technology",
    "G.D. Goenka University",
    "Geeta University",
    "Geetanjali University",
    "G.H. Raisoni University",
    "Girijananda Chowdhury University Assam",
    "G.L.S. University",
    "GNA University",
    "Goa University",
    "Gokhale Institute of Politics & Economics",
    "Gokul Global University",
    "Gondwana University",
    "Gopal Narayan Singh University",
    "Govind Guru Tribal University",
    "Graphic Era",
    "Graphic Era Hill University",
    "GSFC University",
    "Gulbarga University",
    "Gujarat Ayurveda University",
    "Gujarat Biotechnology University",
    "Gujarat Maritime University",
    "Gujarat National Law University",
    "Gujarat Natural Farming and Organic Agricultural University",
    "Gujarat Technlogical University",
    "Gujarat University",
    "Gujarat University of Transplantation Sciences",
    "Gujarat Vidyapith",
    "Guru Angad Dev Veterinary & Animal Sciences University",
    "Guru Ghasidas Vishwavidyalaya",
    "Guru Gobind Singh Indraprastha Vishwavidyalaya",
    "Guru Jambeshwar University of Science and Technology",
    "Guru Kashi University",
    "Guru Nanak Dev University",
    "Gurugram University",
    "Guru Ravidas Ayurved University",
    "Gurukul Kangri Vishvidayala",
    "Harichand Guruchand University",
    "Harcourt Butler Technical University",
    "Haridev Joshi University of Journalism and Mass Communication",
    "Hemchandracharya North Gujarat University",
    "Hemvati Nandan Bahuguna Garhwal University",
    "Hemwati Nandan Bahuguna Medical Education University",
    "Hidayatullah National Law University",
    "Himalayan University",
    "Himalayiya University",
    "Himgiri Zee University",
    "Himachal Pradesh National Law University",
    "Himachal Pradesh Technical University",
    "Himachal Pradesh University",
    "Hindi University",
    "Hindustan Institute of Technology and Science (HITS)",
    "HomoeopathyUniversity",
    "Homi Bhabha National Institute",
    "Hyderabad (SIND) National Collegiate University",
    "ICFAI Foundation for Higher Education",
    "ICFAI University",
    "I.E.C. (India Education Centre) University",
    "I.E.S University",
    "IFTM University",
    "IIHMR University",
    "IIMT University",
    "IILM University",
    "IIS",
    "IMS Unison University",
    "Indian Agricultural Research Institute",
    "Indian Association for the Cultivation of Science (IACS)",
    "Indian Institute of Foreign Trade",
    "Indian Institute of Public Health",
    "Indian Institute of Science",
    "Indian Institute of Space Science and Technology",
    "Indian Institute of Teacher Education",
    "Indian Law Institute",
    "Indian Maritime University",
    "Indian Veterinary Research Institute",
    "Indira Gandhi Delhi Technical University for Women",
    "Indira Gandhi Institute of Development Research",
    "Indira Gandhi Krishi Vishwavidyalaya",
    "Indira Gandhi National Open University",
    "Indira Gandhi University",
    "Indira Kala Sangeet Vishwavidyalaya",
    "Indrashil University",
    "Indus International University",
    "Indus University",
    "Integral University",
    "International Institute for Population Sciences",
    "International Institute of Information Technology",
    "International Sports Univeristy",
    "Invertis University",
    "ISBM University",
    "Islamic University of Science & Technology University",
    "ITM (SLS) Baroda University",
    "ITM University",
    "ITM-Vocational University",
    "Jagadguru Ramanandacharya Rajasthan Sanskrit University",
    "Jagadguru Rambhadracharya Divyang University",
    "Jagan Nath University",
    "Jagran Lakecity University",
    "Jagat Guru Nanak Dev Punjab State Open University",
    "Jai Narain Vyas University",
    "Jain",
    "Jain Vishva Bharati Institute",
    "Jai Prakash Vishwavidyalaya",
    "Jaipur National University",
    "Jadavpur University",
    "Jamia Hamdard",
    "Jamia Mallia Islamia University",
    "Janardan Rai Nagar Rajasthan Vidyapeeth",
    "Jannayak Chandrashekhar University",
    "Jawaharlal Nehru Architecture and Fine Arts University",
    "Jawaharlal Nehru Centre for Advanced Scientific Research",
    "Jawaharlal Nehru Krishi Vishwavidyalaya",
    "Jawaharlal Nehru Technological University",
    "Jawaharlal Nehru Technological University - Gurajada",
    "Jawaharlal Nehru University",
    "Jayoti Vidyapeeth Women’s University",
    "Jaypee Institute of Information Technology",
    "Jaypee University",
    "Jaypee University of Engineering & Technology",
    "Jaypee University of Information Technology",
    "J.C Bose University of Science & Technology",
    "J.E.C.R.C. University",
    "Jeppiaar University",
    "J.G. University",
    "Jharkhand Rai University",
    "Jharkhand Raksha Shakti University",
    "Jharkhand University of Technology",
    "JIS University",
    "Jiwaji University",
    "Jodhpur National University",
    "J.K. Lakshmipat University",
    "JSS Academy of Higher Education & Research",
    "JSS Science & Technology University",
    "J.S. University",
    "Junagarh Agricultural University",
    "Kadi Sarva Vishwavidyalaya",
    "Kakatiya University",
    "Kalahandi University",
    "Kalasalingam Academy of Research and Higher Education",
    "Kalinga Institute of Industrial Technology",
    "Kalinga Institute of Social Sciences",
    "Kalinga University",
    "Kaloji Narayan Rao University of Health Sciences",
    "Kameshwara Singh Darbhanga Sanskrit Vishwavidyalaya",
    "Kamdhenu University",
    "Kannada University",
    "Kannur University",
    "Kanyashree University",
    "Karpagam Academy of Higher Education",
    "Karnavati University",
    "Karunya Institute of Technology and Sciences",
    "“Kaushalya” the Skill University",
    "Kavayitri Bahinbai Chaudhari North Maharashtra University",
    "Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya",
    "Kazi Nazrul University",
    "Kerala Agricultural University",
    "Kerala Kalamandalam",
    "Kerala University of Digital Sciences Innovation and Technology",
    "Kerala University of Fisheries & Ocean Studies",
    "Kerala University of Health Sciences",
    "Kerala Veterinary & Animal Sciences University",
    "Khaja Bandanawaz University",
    "Khallikote University",
    "Khangchendzonga State University",
    "Khongnangthaba University",
    "Khwaja Moinuddin Chishti Urdu, Arabi~Farsi University",
    "King George Medical University",
    "K.K. Modi University",
    "K.K. University",
    "KLE Academy of Higher Education and Research",
    "KLE Technological University",
    "Kolhan University",
    "Koneru Lakshmaiah Education Foundation",
    "Konkan Krishi Vidyapeeth",
    "Krantiguru Shyamji Krishna Verma Kachchh University",
    "KREA University",
    "Krishna Kanta Handiqui State Open University",
    "Krishnaguru Adhyatmik Visvavidyalaya",
    "Krishna University",
    "Krishna Vishwa Vidyapeeth",
    "K.R. Mangalam University",
    "KSGH Music and Performing Arts University",
    "Kumar Bhaskar Varma Sanskrit & Ancient Studies University",
    "Kumaun University",
    "Kurukshetra University",
    "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
    "Kuvempu University",
    "Lakshmibai National Institute of Physical Education",
    "Lakulish Yoga University",
    "Lala Lajpat Rai University of Veterinary & Animal Sciences",
    "Lalit Narayan Mithila University",
    "Lamrin Tech Skills University",
    "Lingaya’s Vidyapeeth",
    "LNCT University",
    "Lokbharati University for Rural Innovation",
    "Lok Jagruti Kendra University",
    "Lords University",
    "Lovely Professional University",
    "Madan Mohan Malviya University of Technology",
    "Madhav University",
    "Madhabdev University",
    "Madhusudan Law University",
    "Madhya Pradesh Medical Science University",
    "Madhyanchal Professional University",
    "Madurai Kamraj University",
    "Magadh University",
    "Maganbhai Adenwala Mahagujarat University",
    "Mahakaushal University",
    "Mahapurusha Srimanta Sankaradeva Viswavidyalaya",
    "Maharaja Agrasen Himalayan Garhwal University",
    "Maharaja Agrasen University",
    "Maharaja Bir Bikram University",
    "Maharaja Bhupinder Singh Punjab Sports University",
    "Maharaja Chhatrasal Bundelkhand Vishwavidyalaya",
    "Maharaja Ganga Singh University",
    "Maharaja Krishnakumarsinji Bhavnagar University",
    "Maharaja Ranjit Singh Punjab Technical University",
    "Maharaja Sayajirao University of Baroda",
    "Maharaja Sriram Chandra Bhanja Deo University",
    "Maharaja Surajmal Brij University",
    "Maharana Pratap Horticultural University",
    "Maharana Pratap University of Agriculture & Technology",
    "Maharani Cluster University",
    "Maharashtra Animal & Fishery Sciences University",
    "Maharashtra Natinoal Law University",
    "Maharashtra State Skills University",
    "Maharashtra University of Health Sciences",
    "Maharishi Arvind University",
    "Maharishi Balmiki Sanskrit University",
    "Maharishi Dayanand Saraswati University",
    "Maharishi Dayanand University",
    "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
    "Maharishi Markandeshwar University",
    "Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya",
    "Maharishi University of Information Technology",
    "Maharishi University of Management and Technology",
    "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalay",
    "Mahatma Gandhi Central University",
    "Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya",
    "Mahatma Gandhi Kashi Vidyapeeth",
    "Mahatma Gandhi Udyanikee Evam Vanikee Vishwavidyalaya",
    "Mahatma Gandhi University",
    "Mahatma Gandhi University of Medical Sciences & Technology",
    "Mahatma Jyoti Rao Phule University",
    "Mahatma Jyotiba Phule Rohilkhand University",
    "Mahatma Phule Krishi Vidyapeeth",
    "Mahayogi Gorakhnath University Gorakhpur",
    "Mahendra University",
    "Mahindra University Bahadurpaly(V)",
    "Majuli University of Culture",
    "Makhanlal Chaturvedi National University of Journalism and Communication",
    "Malla Reddy University",
    "Malwanchal University",
    "Manav Bharti University",
    "Manav Rachna International Institute of Research & Studies",
    "Manav Rachna University",
    "Mandsaur University",
    "Mangalayatan University",
    "Mangalore University",
    "Manipal Academy of Higher Education",
    "Manipal University",
    "Manipur International University",
    "Manipur Technical University",
    "Manipur University",
    "Manipur University of Culture",
    "Manonmaniam Sundarnar University",
    "Mansarovar Global University",
    "Marathwada Agricultural University",
    "Martin Luther Christian University",
    "Marwadi University",
    "Mata Gujri University",
    "MATS University",
    "Maulana Abul Kalam Azad University of Technology",
    "Maulana Azad National Urdu University",
    "Maulana Azad University",
    "Maulana Mazharul Haque Arabic & Persian University",
    "M.B.M. University",
    "Medi-Caps University",
    "Medhavi Skills University",
    "Meenakshi Academy of Higher Education and Research",
    "Mewar University",
    "MGM Institute of Health Sciences",
    "MGM University",
    "MIT Art Design & Technology University",
    "Mizoram University",
    "Mody University of Science and Technology",
    "Mohammad Ali Jauhar University",
    "Mohan Lal Sukhadia University",
    "Monad University",
    "Monark University",
    "Morarji Desai National Institute of Yoga",
    "Motherhood University",
    "Mother Teresa Women’s University",
    "M.P.Bhoj (open) University",
    "M.S. Ramaiah University of Applied Sciences",
    "Munger University",
    "Murshidabad University",
    "M.V.N. University",
    "Nagaland University",
    "Nalanda Open University",
    "Nalanda University",
    "NALSAR University of Law",
    "Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya",
    "Narendra Deo University of Agriculture & Technology",
    "Narsee Monjee Institute of Management Studies",
    "National Brain Research Centre",
    "National Dairy Research Institute",
    "National Institute of Ayurveda (NIA)",
    "National Institute of Educational Planning and Administration",
    "National Institute of Food Technology, Entrepreneurship & Management (NIFTEM)",
    "National law School of India University",
    "National Law Institute University",
    "National Law University",
    "National Law University and Judicial Academy",
    "National Museum Institute of History of Art, Conservation and Museology",
    "National Rail and Transportation Institute (NRTI)",
    "National Sports University",
    "National University of Study & Research in Law",
    "Nava Nalanda Mahavihara",
    "Navrachana University",
    "Navsari Agricultural University",
    "Nehru Gram Bharati",
    "Netaji Subhas University",
    "Netaji Subhas University of Technology",
    "Netaji Subhash Open University",
    "NICMAR University",
    "NIILM University",
    "NIIT University",
    "Nilamber-Pitamber University",
    "Nims University Rajasthan",
    "Nirma University",
    "Nirwan University",
    "NITTE",
    "Nizam’s Institute of Medical Sciences",
    "Noble University",
    "Noida International University",
    "Noorul Islam Centre for Higher Education",
    "North East Adventist University",
    "North East Christian University",
    "North-Eastern Hill University",
    "North East Frontier Technical University",
    "North Eastern Regional Institute of Science & Technology",
    "Nrupathunga University",
    "Odisha State Open University",
    "Odisha University of Technology and Research",
    "Om Sterling Global University",
    "O.P. Jindal Global University",
    "O.P. Jindal University",
    "OPJS University",
    "Oriental University",
    "Orissa University of Agriculture & Technology",
    "Osmania University",
    "Pacific Academy of Higher Education & Research University",
    "Pacific Medical University",
    "Padmashree Dr. D.Y. Patil Vidyapeeth",
    "PalamuruUniversity",
    "Pandit Deendayal Energy University",
    "Pandit Deendayal Upadhyaya Shekhawati University",
    "Pandit Lakhmi Chand State University of Performing and Visual Arts",
    "Pandit S.N. Shukla University",
    "Pandit Sundar Lal Sharma (Open) University Chhatisgarh",
    "Panjab University",
    "Parul University",
    "Patliputra University",
    "Patna University",
    "PDM University",
    "People’s University",
    "Periyar Maniammai Institute of Science & Technology (PMIST)",
    "Periyar University",
    "PES University",
    "P.K. University",
    "Plaksha University Punjab",
    "Plastindia International University",
    "Pondicherry University",
    "Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)",
    "Pooja Desai",
    "Poornima University",
    "Potti Sreeramulu Telugu University",
    "P.P. Savani University",
    "Pragjyotishpur University",
    "Pragyan International University",
    "Pratap University",
    "Pravara Institute of Medical Sciences",
    "Presidency University",
    "Priya Sharma",
    "Professor Jayashankar Telangana State Agricultural University",
    "Prof. Rajendra Singh (Rajju Bhaiya) University",
    "Puducherry Technological University",
    "Punjab Agricultural University",
    "Punjab Engineering College",
    "Punjabi University",
    "Punyashlok Ahilyadevi Holkar Solapur University",
    "Purnea University",
    "Quantum University",
    "Rabindra Bharati University",
    "Rabindranath Tagore University",
    "Radha Govind University",
    "Raffles University",
    "Raichur University",
    "Raiganj University",
    "Rai Technology University",
    "Rai University",
    "Raja Mahendra Pratap Singh State University",
    "Raja Mansingh Tomar Music & Arts University",
    "Raja Shankar Shah University",
    "Rajasthan Agricultural University",
    "Rajasthan Ayurveda University",
    "Rajasthan ILD Skills University (RISU)",
    "Rajasthan Technical University",
    "Rajasthan University of Health Sciences",
    "Rajasthan University of Veterinary & Animal Sciences",
    "Rajesh Kumar",
    "Raj Rishi Bhartrihari Matsya University",
    "Rajiv Gandhi National Aviation University",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
    "Rajiv Gandhi University",
    "Rajiv Gandhi University of Health Sciences",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Rajiv Gandhi University of Knowledge Technologies Andhra Pradesh",
    "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
    "Rama Devi Women’s University",
    "Rama University",
    "Ramakrishna Mission Vivekananda Educational and Research Institute",
    "Ramchandra Chandravansi University",
    "Ram Krishana Dharmarth Foundation University",
    "Ranchi University",
    "Rani Channamma University",
    "Rani Durgavati Vishwavidyalaya",
    "Rani Lakshmi Bai Central Agricultural University",
    "Rani Rashmoni Green University",
    "Ras Bihari Bose Subharti University",
    "Ravenshaw University",
    "Rayalaseema University",
    "Rayat Bahra University",
    "Rajendra University",
    "Renaissance University",
    "Reva University",
    "RIMT University",
    "Rishihood University",
    "R.K. University",
    "RKDF University",
    "R.N.B. Global University",
    "Rohan Verma",
    "RV University",
    "Sabarmati University",
    "Sadhu Ram Chand Murmu University of Jhargram",
    "Sage University",
    "Sai Nath University",
    "Sai Tirupati University",
    "Sai University",
    "SAM Global University",
    "Sambalpur University",
    "Sam Higginbottom Institute of Agriculture, Technology & Sciences",
    "Sampurnanand Sanskrit Vishwavidyalaya",
    "Sanchi University of Buddhist-Indic Studies",
    "Sandip University",
    "Sangai International University",
    "Sangam University",
    "Sanjay Ghodawat University",
    "Sanjeev Agrawal Global Educational University",
    "Sankalchand Patel University",
    "Sanskriti University",
    "Sant Baba Bhag Singh University",
    "Sant Gadge Baba Amravati University",
    "Sant Gahira Guru Vishwavidyalaya",
    "Sant Longowal Institute of Engineering and Technology (SLIET)",
    "Santosh",
    "Sardar Beant Singh State University",
    "Sardar Bhagwan Singh University",
    "Sardar Krushinagar Dantiwada Agricultural University",
    "Sardar Patel University",
    "Sardar Patel University Mandi",
    "Sardar Patel University of Police, Security & Criminal Justice",
    "Sardar Vallabh Bhai Patel University of Agriculture & Technology",
    "Sarla Birla University",
    "Sarvepalli Radhakrishnan University",
    "Sarvajanik University",
    "Sathyabama Institute of Science and Technology",
    "Satavahana University",
    "Saurashtra University",
    "Saveetha Amaravati University",
    "Saveetha Institute of Medical and Technical Sciences",
    "Savitribai Phule Pune University",
    "Seacom Skills University",
    "Shaheed Bhagat Singh State University",
    "Shaheed Mahendra Karma Vishwavidyalaya",
    "Shaheed Nandkumar Patel Vishwavidyalaya",
    "Shanmugha Arts, Science, Technology and Research Academy (SASTRA)",
    "Sharda University",
    "Sharnbasva University",
    "Sher-e-Kashmir University of Agricultural Science & Technology",
    "Shiksha ‘O’ Anusandhan",
    "Shivaji University",
    "Shiv Nadar",
    "Shiv Nadar University",
    "Shobhit Institute of Engineering & Technology",
    "Shobhit University",
    "Shoolini University of Biotechnology and Management Sciences",
    "Shree Guru Gobind Singh Tricentenary University",
    "Shree Somnath Sanskrit University",
    "Shree Sankaracharya University of Sanskrit",
    "Shreyarth University",
    "Shri Dharmasthala Manjunatheshwara University",
    "Shri Govind Guru University",
    "Shri Guru Granth Sahib World University",
    "Shri Guru Ram Rai University",
    "Shri Guru Ram Das University of Health Sciences",
    "Shri Guru Teg Bahadur State University of Law",
    "Shri Jagadhguru Murugarajendra University",
    "Shri Jagannath Sanskrit Vishwavidyalaya",
    "Shri Jagdish Prasad Jhabarmal Tibrewala University",
    "Shri Kallaji Vedic Vishvavidyalaya",
    "Shri Khushal Das University",
    "Shri Krishna AYUSH University",
    "Shri Krishna University",
    "Shri Lal Bahadur Shastri National Sanskrit University",
    "Shri Mata Vaishno Devi University",
    "Shri Ramasamy Memorial University",
    "Shri Ramswaroop Memorial University",
    "Shridhar University",
    "Shri Rawatpura Sarkar University",
    "Shri Shankaracharaya Professional University",
    "Shri Vaishnav Vidyapeeth Vishwavidyalaya",
    "Shri Venkateshwara University",
    "Shri Vishwakarma Skill University",
    "Siddharth University",
    "Sidho-Kanho-Birsha University",
    "Sido Kanhu Murmu University",
    "Sikkim Alpine University",
    "Sikkim International University",
    "Sikkim Manipal University",
    "Sikkim National Law University",
    "Sikkim Professional University",
    "Sikkim Skill University",
    "Sikkim University",
    "Silver Oak University",
    "Sindhu Central University",
    "Singhania University",
    "Sir Padmapat Singhania University",
    "Sister Nivedita University",
    "SKIPS University",
    "Smt. Nathibai Damodar Thackersey Women’s University",
    "Sneha Gupta",
    "Soban Singh Jeena University",
    "Somaiya Vidyavihar University",
    "South Asian University",
    "Spicer Adventist University",
    "Sreenarayanaguru Open University",
    "Sri Aurobindo University",
    "Sri Balaji University",
    "Sri Balaji Vidyapeeth",
    "Sri Chandrasekharandra Saraswati Vishwa Mahavidyalaya",
    "Sri Devraj Urs Academy of Higher Education and Research",
    "Sri Dev Suman Uttarakhand Vishwavidyalay",
    "Sri Jagadhguru Murugarajendra University",
    "Sri Konda Laxman Telangana State Horticultural University",
    "Sri Krishnadevaraya University",
    "Sri Padmavati Mahila Vishwavidyalayam",
    "Sri Ramachandra Medical College and Research Institute",
    "Sri Sai University",
    "Sri Sathya Sai Institute of Higher Learning",
    "Sri Sathya Sai University for Human Excellence",
    "Sri Satya Sai University of Technology & Medical Sciences",
    "Sri Siddhartha Academy of Higher Education",
    "Sri Sri Anirudhadeva Sports University",
    "Sri Sri University",
    "Sri Venkateswara Institute of Medical Sciences",
    "Sri Venkateswara University",
    "Sri Venkateswara Vedic University",
    "Sri Venkateswara Veterinary University",
    "Srimanta Sankaradeva University of Health Sciences",
    "Srinath University",
    "Srinivas University",
    "SRM Institute of Sciences and Technology",
    "SRM University",
    "SR University",
    "Starex University",
    "St. Joseph’s University",
    "St. Joseph University",
    "St. Peter’s Institute of Higher Education and Research",
    "St. Xavier’s University",
    "Sumandeep Vidyapeeth",
    "Sunrise University",
    "Surajmal University",
    "Sardar Beant Singh State University",
    "Suresh Gyan Vihar University",
    "Sushant University",
    "Swami Vivekanand Subharti University",
    "Swami Vivekananda University",
    "Swami Vivekananda Yoga Anusandhana Sansthana",
    "Swami Vivekanand University",
    "Swaminarayan University",
    "Swarnim Gujarat Sports University",
    "Swarnim Startup & Innovation University",
    "Symbiosis International",
    "Symbiosis Skills and Professional University",
    "Symbiosis University of Applied Sciences",
    "Tamilnadu Agricultural University",
    "Tamilnadu Dr. Ambedkar Law University",
    "Tamilnadu Dr. M.G.R. Medical University",
    "Tamilnadu Fisheries University",
    "Tamilnadu Music and Fine Arts University",
    "Tamilnadu National Law School",
    "Tamilnadu Open University",
    "Tamilnadu Physical Education and Sports University",
    "Tamil Nadu Teacher Education University",
    "Tamilnadu Veterinary & Animal Sciences University",
    "Tamil University",
    "Tantia University",
    "Tata Institute of Fundamental Research",
    "Tata Institute of Social Sciences",
    "Team Lease Skills University",
    "Techno Global University",
    "Techno India University",
    "Teerthanker Mahaveer University",
    "Telangana University",
    "TERI School of Advanced Studies",
    "Tezpur University",
    "Thapar Institute of Engineering & Technology",
    "The Assam Kaziranga University",
    "The Assam Royal Global University",
    "The Central Sanskrit University",
    "The Charutar Vidya Mandal (CVM) University",
    "The Global Open University",
    "The Global University",
    "The Glocal University",
    "The I.K. Gujaral Punjab Technical University",
    "The Indira Gandhi Technological & Medical Sciences University",
    "The LNM Institute of Information Technology",
    "The Maharaja Bhupinder Singh Punjab Sports University",
    "The National Sanskrit University",
    "The Neotia University",
    "The Northcap University",
    "The Rajiv Gandhi National University of Law",
    "The Rashtrasant Tukadoji Maharaj Nagpur University",
    "The Sanskrit College and University",
    "The University of Trans-Disciplinary Health Sciences and Technology",
    "The West Bengal National University of Juridical Science",
    "The West Bengal University of Health Sciences",
    "The West Bengal University of Teachers’ Training, Education Planning and Administration",
    "Thiruvalluvar University",
    "Thunchath Ezhuthachan Malayalam University",
    "Tilak Maharashtra Vidyapeeth",
    "T.M. University",
    "Transstadia University",
    "Tripura University",
    "Tumkur University",
    "UKA Tarsadia University",
    "United University",
    "University of Allahabad",
    "University of Burdwan",
    "University of Calcutta",
    "University of Calicut",
    "University of Delhi",
    "University of Engineering & Management",
    "University of Engineering and Technology Roorkee",
    "University of Gour Banga",
    "University of Hyderabad",
    "University of Jammu",
    "University of Kalyani",
    "University of Kashmir",
    "University of Kerala",
    "University of Kota",
    "University of Ladakh",
    "University of Lucknow",
    "University of Madras",
    "University of Mumbai",
    "University of Mysore",
    "University of North Bengal",
    "University of Patanjali",
    "University of Petroleum and Energy Studies",
    "University of Rajasthan",
    "University of Science & Technology",
    "University of Technology",
    "U.P. King George’s University of Dental Science",
    "UPL University of Sustainable Technology",
    "U.P. Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidyalaya Evam Go-Anusandhan Sansthan",
    "U.P. Rajarshi Tandon Open University",
    "Usha Martin University",
    "Utkal University",
    "Utkal University of Culture",
    "Uttaranchal University",
    "Uttar Banga Krishi Vishwavidyalaya",
    "Uttarakhand Ayurved University",
    "Uttarakhand Open University",
    "Uttarakhand Sanskrit University",
    "Uttrakhand Technical University",
    "Vanita Vishram Women’s University",
    "Vardhman Mahaveer Open University",
    "Veer Bahadur Singh Purvanchal University",
    "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry",
    "Veer Kunwar Singh University",
    "Veer Narmad South Gujarat University",
    "Veer Surendra Sai Institute of Medical Sciences and Research",
    "Veer Surendra Sai University of Technology",
    "Vel’s Institute of Science, Technology & Advanced Studies (VISTAS)",
    "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology",
    "Venkateshwara Open University",
    "Vidyasagar University",

    "Vidyashilp University",
    "Vignan's Foundation for Science, Technology and Research",
    "Vijaybhoomi University",
    "Vikram University",
    "Vikrama Simhapuri University",
    "Vikrant University",
    "Vinayaka Mission’s Research Foundation",
    "Vinoba Bhave University",
    "Vishwa Bharati University",
    "Vishwakarma University",
    "Visveswaraiah Technological University",
    "VIT Bhopal University",
    "VIT-AP University",
    "Vivekananda Global University",
    "West Bengal State University",
    "West Bengal University of Animal and Fishery Sciences",
    "William Carey University",
    "World University of Design",
    "Woxsen University",
    "XIM University",
    "YBN University",
    "Yenepoya",
    "Yogi Vemana University",
    "Adesh University",
    "Adichunchanagiri University",
    "Agriculture University",
    "Ahmedabad University",
    "Ajeenkya D.Y. Patil University",
    "Akal University",
    "A.K.S. University",
    "Amrita Vishwa Vidyapeetham",
    "Annamalai University",
    "Apex University",
    "Arunachal University of Studies",
    "Atal Bihari Vajpayee Vishwavidyalaya",
    "Atmiya University",
    "AURO University of Hospitality and Management",
    "Avinashilingam Institute for Home Science & Higher Education for Women",
    "Ayush and Health Sciences University of Chhattisgarh",
    "Azim Premji University",
    "Baba Farid University of Health Sciences",
    "Baba Mast Nath University",
    "Bahra University",
    "Banasthali Vidyapith",
    "Bangalore University",
    "Bareilly International University",
    "Barkatullah University",
    "Bennett University",
    "Berhampur University",
    "Bhagwant University",
    "Bharathiar University",
    "Bharathidasan University",
    "Bharati Vidyapeeth",
    "Bhatkhande Music Institute",
    "Bhupal Nobles University",
    "Bikaner Technical University",
    "Birla Institute of Technology & Science",
    "BLDE University",
    "BML Munjal University",
    "B.S. Abdur Rahman Crescent Institute of Science and Technology",
    "Bundelkhand University",
    "Capital University",
    "Career Point University",
    "Central University of Gujarat",
    "Central University of Haryana",
    "Central University of Himachal Pradesh",
    "Central University of Jammu",
    "Central University of Jharkhand",
    "Central University of Karnataka",
    "Central University of Kashmir",
    "Central University of Kerala",
    "Central University of Odisha",
    "Central University of Punjab",
    "Central University of Rajasthan",
    "Central University of South Bihar",
    "Central University of Tamil Nadu",
    "Centurion University of Technology and Management",
    "CEPT University",
    "Chaitanya",
    "Chanakya National Law University",
    "Chandigarh University",
    "Charotar University of Science & Technology",
    "Chaudhary Bansi Lal University",
    "Chaudhary Charan Singh Haryana Agricultural University",
    "Chaudhary Devi Lal University",
    "Chaudhary Ranbir Singh University",
    "Chennai Mathematical Institute",
    "Chettinad Academy of Research and Education",
    "Children’s University",
    "Chinmaya Vishwavidyapeeth",
    "Chitkara University",
    "Christ University",
    "CMR University",
    "Cochin University of Science and Technology",
    "Cooch Behar Panchanan Barma University",
    "Cotton University",
    "C.U. Shah University",
    "Dakshin Dinajpur University",
    "Damodaram Sanjivayya National Law University",
    "Datta Meghe Institute of Medical Sciences",
    "Dayananda Sagar University",
    "Deccan College Post-Graduate and Research Institute",
    "Deenbandhu Chhotu Ram University of Science and Technology",
    "Delhi Pharmaceutical Sciences and Research University",
    "Delhi Technological University",
    "Desh Bhagat University",
    "Dev Sanskriti Vishwavidyalaya",
    "Devi Ahilya Vishwavidyalaya",
    "Dhanalakshmi Srinivasan University",
    "Dharmsinh Desai University",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "Diamond Harbour Women's University",
    "Dibrugarh University",
    "DIT University",
    "Doon University",
    "Dr. A.P.J. Abdul Kalam Technical University",
    "Dr. B.R. Ambedkar National Law University",
    "Dr. B.R. Ambedkar University of Social Sciences",
    "Dr. D.Y. Patil Vidyapeeth",
    "Dr. M.G.R. Educational and Research Institute",
    "Dr. N.T.R. University of Health Sciences",
    "Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
    "Dr. Ram Manohar Lohia Avadh University",
    "Dr. Ram Manohar Lohiya National Law University",
    "Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University",
    "Dr. Y.S. Parmar University of Horticulture and Forestry",
    "Dravidian University",
    "D.Y. Patil International University",
    "Eternal University",
    "FLAME University",
    "Forest Research Institute",
    "Fakir Mohan University",
    "Galgotias University",
    "Gandhigram Rural Institute",
    "Gandhi Institute of Technology and Management",
    "Gangadhar Meher University",
    "Ganpat University",
    "Gauhati University",
    "Gautam Buddha University",
    "G.B. Pant University of Agriculture and Technology",
    "G.D. Goenka University",
    "GITAM University",
    "Gokhale Institute of Politics and Economics",
    "Gondwana University",

    "Graphic Era Hill University",
    "Gujarat Ayurveda University",
    "Gujarat National Law University",
    "Gujarat Technological University",
    "Gujarat University",
    "Gujarat Vidyapith",
    "Gulbarga University",
    "Guru Angad Dev Veterinary and Animal Sciences University",
    "Guru Ghasidas Vishwavidyalaya",
    "Guru Jambheshwar University of Science and Technology",
    "Guru Kashi University",
    "Guru Nanak Dev University",
    "Gurukula Kangri Vishwavidyalaya",
    "Hemchandracharya North Gujarat University",
    "Hemvati Nandan Bahuguna Garhwal University",
    "Hidayatullah National Law University",
    "Himachal Pradesh University",
    "Himgiri Zee University",
    "Hindustan Institute of Technology and Science",
    "Homi Bhabha National Institute",
    "ICFAI Foundation for Higher Education",
    "IIHMR University",
    "IIMT University",
    "I. K. Gujral Punjab Technical University",
    "Indian Agricultural Research Institute",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "Indian Institute of Foreign Trade",
    "Indian Institute of Information Technology",
    "Indian Institute of Information Technology, Allahabad",
    "Indian Institute of Information Technology and Management, Gwalior",
    "Indian Institute of Science",
    "Indian Institute of Science Education and Research, Bhopal",
    "Indian Institute of Science Education and Research, Kolkata",
    "Indian Institute of Science Education and Research, Mohali",
    "Indian Institute of Science Education and Research, Pune",
    "Indian Institute of Science Education and Research, Thiruvananthapuram",
    "Indian Institute of Space Science and Technology",
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Bhubaneswar",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Gandhinagar",
    "Indian Institute of Technology Guwahati",
    "Indian Institute of Technology Hyderabad",
    "Indian Institute of Technology Indore",
    "Indian Institute of Technology Jodhpur",
    "Indian Institute of Technology Kanpur",
    "Indian Institute of Technology Kharagpur",
    "Indian Institute of Technology Madras",
    "Indian Institute of Technology Mandi",
    "Indian Institute of Technology Patna",
    "Indian Institute of Technology Roorkee",
    "Indian Institute of Technology Ropar",
    "Indian Law Institute",
    "Indian Maritime University",
    "Indian Statistical Institute",
    "Indian Veterinary Research Institute",
    "Indira Gandhi Delhi Technical University for Women",
    "Indira Gandhi Institute of Development Research",
    "Indira Gandhi National Open University",
    "Indira Gandhi National Tribal University",
    "Indira Kala Sangeet Vishwavidyalaya",
    "Indraprastha Institute of Information Technology, Delhi",
    "Indus University",
    "Institute of Advanced Research",
    "Institute of Armament Technology",
    "Institute of Chemical Technology",
    "Institute of Liver and Biliary Sciences",
    "Integral University",
    "International Institute for Population Sciences",
    "Invertis University",
    "Islamic University of Science and Technology",
    "Jadavpur University",
    "Jagadguru Ramanandacharya Rajasthan Sanskrit University",
    "Jagadguru Rambhadracharya Handicapped University",
    "Jagan Nath University",
    "Jagran Lakecity University",
    "Jai Narain Vyas University",
    "Jain Vishva Bharati Institute",
    "Jaipur National University",
    "Jamia Hamdard",
    "Jamia Millia Islamia",
    "Jananayak Chandrashekhar University",
    "Janardan Rai Nagar Rajasthan Vidyapeeth",
    "Jawaharlal Institute of Postgraduate Medical Education and Research",
    "Jawaharlal Nehru Centre for Advanced Scientific Research",
    "Jawaharlal Nehru Krishi Vishwavidyalaya",
    "Jawaharlal Nehru University",
    "Jaypee Institute of Information Technology",
    "Jaypee University of Engineering and Technology",
    "Jaypee University of Information Technology",
    "J.C. Bose University of Science and Technology, YMCA",
    "JECRC University",
    "JIS University",
    "Jiwaji University",
    "Jodhpur National University",
    "JSS Academy of Higher Education and Research",
    "Kalasalingam Academy of Research and Education",
    "Kalinga Institute of Industrial Technology",
    "Kalinga Institute of Social Sciences",
    "Kameshwar Singh Darbhanga Sanskrit University",
    "Kannur University",
    "Karnatak University",
    "Karnataka State Law University",
    "Karnataka State Open University",
    "Karnataka State Women's University",
    "Karnataka Veterinary, Animal and Fisheries Sciences University",
    "Karpagam Academy of Higher Education",
    "Karunya Institute of Technology and Sciences",
    "Kavayitri Bahinbai Chaudhari North Maharashtra University",
    "Kazi Nazrul University",
    "Kevempu University",
    "Khallikote University",
    "Khwaja Moinuddin Chishti Language University",
    "King George's Medical University",
    "KLE University",
    "Koneru Lakshmaiah Education Foundation",
    "Krishna Kanta Handiqui State Open University",
    "Krishna University",
    "Kumar Bhaskar Varma Sanskrit and Ancient Studies University",
    "Kumaun University",
    "Kurukshetra University",
    "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
    "Lakshmibai National Institute of Physical Education",
    "Lalit Narayan Mithila University",
    "LNM Institute of Information Technology",
    "Lovely Professional University",
    "Lucknow University",
    "Madan Mohan Malaviya University of Technology",
    "Madhav University",
    "Madhya Pradesh Bhoj Open University",
    "Madhya Pradesh Medical Science University",
    "Madurai Kamaraj University",
    "Magadh University",
    "Maharaja Chhatrasal Bundelkhand University",
    "Maharaja Ganga Singh University",
    "Maharaja Krishnakumarsinhji Bhavnagar University",
    "Maharaja Ranjit Singh State Technical University",
    "Maharaja Sayajirao University of Baroda",
    "Maharana Pratap University of Agriculture and Technology",
    "Maharashtra Animal and Fishery Sciences University",
    "Maharashtra National Law University, Mumbai",
    "Maharashtra National Law University, Nagpur",
    "Maharashtra University of Health Sciences",
    "Maharishi Dayanand Saraswati University",
    "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
    "Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya",
    "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya",
    "Mahatma Gandhi Central University",
    "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya",
    "Mahatma Gandhi Kashi Vidyapith",
    "Mahatma Gandhi University",
    "Mahatma Gandhi University of Medical Sciences & Technology",
    "Mahatma Jyotiba Phule Rohilkhand University",
    "Mahatma Phule Krishi Vidyapeeth",
    "Makhanlal Chaturvedi National University of Journalism and Communication",
    "Malaviya National Institute of Technology",
    "Manav Rachna University",
    "Manipur University",
    "Manonmaniam Sundaranar University",
    "Marathwada Agricultural University",
    "Martin Luther Christian University",
    "MATS University",
    "Maulana Abul Kalam Azad University of Technology",
    "Maulana Azad National Institute of Technology",
    "Maulana Azad National Urdu University",
    "Maulana Mazharul Haque Arabic and Persian University",
    "Meenakshi Academy of Higher Education and Research",
    "Mewar University",
    "MGM Institute of Health Sciences",
    "Mizoram University",
    "M. J. P. Rohilkhand University",
    "Mohanlal Sukhadia University",
    "Mother Teresa Women's University",
    "Motilal Nehru National Institute of Technology",
    "Nagaland University",
    "NALSAR University of Law",
    "Narendra Deva University of Agriculture and Technology",
    "Narsee Monjee Institute of Management Studies",
    "National Institute of Design",
    "National Institute of Fashion Technology",
    "National Institute of Mental Health and Neurosciences",
    "National Institute of Pharmaceutical Education and Research, Ahmedabad",
    "National Institute of Pharmaceutical Education and Research, Guwahati",
    "National Institute of Pharmaceutical Education and Research, Hajipur",
    "National Institute of Pharmaceutical Education and Research, Hyderabad",
    "National Institute of Pharmaceutical Education and Research, Kolkata",
    "National Institute of Pharmaceutical Education and Research, Raebareli",
    "National Institute of Pharmaceutical Education and Research, S.A.S. Nagar",
    "National Institute of Technology, Agartala",
    "National Institute of Technology, Arunachal Pradesh",
    "National Institute of Technology, Calicut",
    "National Institute of Technology, Delhi",
    "National Institute of Technology, Durgapur",
    "National Institute of Technology, Goa",
    "National Institute of Technology, Hamirpur",
    "National Institute of Technology, Jalandhar",
    "National Institute of Technology, Jamshedpur",
    "National Institute of Technology, Karnataka",
    "National Institute of Technology, Kurukshetra",
    "National Institute of Technology, Manipur",
    "National Institute of Technology, Meghalaya",
    "National Institute of Technology, Mizoram",
    "National Institute of Technology, Nagaland",
    "National Institute of Technology, Patna",
    "National Institute of Technology, Puducherry",
    "National Institute of Technology, Raipur",
    "National Institute of Technology, Rourkela",
    "National Institute of Technology, Sikkim",
    "National Institute of Technology, Silchar",
    "National Institute of Technology, Srinagar",
    "National Institute of Technology, Tiruchirappalli",
    "National Institute of Technology, Uttarakhand",
    "National Institute of Technology, Warangal",
    "National Law School of India University",
    "National Law University, Delhi",
    "National Law University, Jodhpur",
    "National Law University, Odisha",
    "National University of Advanced Legal Studies",
    "National University of Study and Research in Law",
    "Nava Nalanda Mahavihara",
    "Navsari Agricultural University",
    "Netaji Subhas Open University",
    "Nehru Gram Bharati Vishwavidyalaya",
    "Nirma University",
    "Nitte University",
    "Nizam's Institute of Medical Sciences",
    "North-Eastern Hill University",
    "North Bengal University",
    "North Gujarat University",
    "North Maharashtra University",
    "Odisha University of Agriculture and Technology",
    "Osmania University",
    "Padmashree Dr. D. Y. Patil Vidyapeeth",
    "Palamuru University",
    "Pandit Deendayal Petroleum University",
    "Pandit Ravishankar Shukla University",
    "Panjab University, Chandigarh",
    "Parul University",
    "Patna University",
    "Periyar University",
    "PES University",
    "Pokhara University",
    "Pondicherry University",
    "Ponnaiyah Ramajayam Institute of Science and Technology",
    "Post Graduate Institute of Medical Education and Research",
    "Potti Sreeramulu Telugu University",
    "Presidency University, Chennai",
    "Presidency University, Kolkata",
    "Pt. Ravishankar Shukla University",
    "Punjab Agricultural University",
    "Punjab Technical University",
    "Punjabi University, Patiala",
    "Punyashlok Ahilyadevi Holkar Solapur University",
    "Rabindra Bharati University",
    "Raiganj University",
    "Rajiv Gandhi Institute of Petroleum Technology",
    "Rajiv Gandhi National University of Law",
    "Rajiv Gandhi University",
    "Rajiv Gandhi University of Health Sciences",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya",
    "Ramakrishna Mission Vivekananda University",
    "Ranchi University",
    "Rani Channamma University, Belagavi",
    "Rani Durgavati Vishwavidyalaya",
    "Rashtrasant Tukadoji Maharaj Nagpur University",
    "Rashtriya Sanskrit Sansthan",
    "Rashtriya Sanskrit Vidyapeetha",
    "Ravenshaw University",
    "REVA University",
    "RKDF University",
    "Sambalpur University",
    "Sampurnanand Sanskrit Vishwavidyalaya",
    "Sanjay Gandhi Postgraduate Institute of Medical Sciences",
    "Sant Gadge Baba Amravati University",
    "Sant Longowal Institute of Engineering and Technology",
    "Sardar Patel University",
    "Sardar Vallabhbhai National Institute of Technology",
    "Sardar Vallabhbhai Patel University of Agriculture and Technology",
    "Sardarkrushinagar Dantiwada Agricultural University",
    "SASTRA University",
    "Sathyabama University",
    "Saurashtra University",
    "Saveetha University",
    "School of Planning and Architecture, Bhopal",
    "School of Planning and Architecture, Delhi",
    "School of Planning and Architecture, Vijayawada",
    "Shanmugha Arts, Science, Technology & Research Academy",
    "Sharda University",
    "Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu",
    "Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir",
    "Shivaji University",
    "Shoolini University of Biotechnology and Management Sciences",
    "Shreemati Nathibai Damodar Thackersey Women's University",
    "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeeth",
    "Shri Mata Vaishno Devi University",
    "Sido Kanhu Murmu University",
    "Sikkim University",
    "Siksha 'O' Anusandhan",
    "Singhania University",
    "Solapur University",
    "South Asian University",
    "Sree Chitra Tirunal Institute for Medical Sciences and Technology",
    "Sree Sankaracharya University of Sanskrit",
    "Sri Agrasen University",
    "Sri Balaji Vidyapeeth",
    "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya",
    "Sri Devraj Urs Academy of Higher Education and Research",
    "Sri Guru Granth Sahib World University",
    "Sri Guru Ram Das University of Health Sciences",
    "Sri Krishnadevaraya University",
    "Sri Padmavati Mahila Visvavidyalayam",
    "Sri Ramachandra University",
    "Sri Sathya Sai Institute of Higher Learning",
    "Sri Venkateswara Institute of Medical Sciences",
    "Sri Venkateswara University",
    "Sri Venkateswara Veterinary University",
    "SRM University",
    "St. Xavier's University, Kolkata",
    "Swami Keshwanand Rajasthan Agricultural University",
    "Swami Ramanand Teerth Marathwada University",
    "Swami Vivekanand Subharti University",
    "Symbiosis International University",
    "Tamil Nadu Agricultural University",
    "Tamil Nadu Dr. Ambedkar Law University",
    "Tamil Nadu Dr. M.G.R. Medical University",
    "Tamil Nadu Fisheries University",
    "Tamil Nadu Music and Fine Arts University",
    "Tamil Nadu National Law School",
    "Tamil Nadu Open University",
    "Tamil Nadu Physical Education and Sports University",
    "Tamil Nadu Veterinary and Animal Sciences University",
    "Tamil University",
    "Tata Institute of Social Sciences",
    "Tezpur University",
    "Thapar University",
    "The English and Foreign Languages University",
    "The Gandhigram Rural Institute",
    "The LNM Institute of Information Technology",
    "The West Bengal National University of Juridical Sciences",
    "Thiruvalluvar University",
    "Tilak Maharashtra Vidyapeeth",
    "Tilka Manjhi Bhagalpur University",
    "Tripura University",
    "Tumkur University",
    "University of Agricultural Sciences, Bangalore",
    "University of Agricultural Sciences, Dharwad",
    "University of Agricultural Sciences, Raichur",
    "University of Burdwan",
    "University of Calcutta",
    "University of Calicut",
    "University of Delhi",
    "University of Gour Banga",
    "University of Horticultural Sciences, Bagalkot",
    "University of Hyderabad",
    "University of Jammu",
    "University of Kalyani",
    "University of Kashmir",
    "University of Kerala",
    "University of Kota",
    "University of Lucknow",
    "University of Madras",
    "University of Mumbai",
    "University of Mysore",
    "University of North Bengal",
    "University of Patanjali",
    "University of Petroleum and Energy Studies",
    "University of Pune",
    "University of Rajasthan",
    "University of Science and Technology, Meghalaya",
    "University of Agricultural and Horticultural Sciences, Shimoga",
    "U.P. Rajarshi Tandon Open University",
    "Utkal University",
    "Utkal University of Culture",
    "Uttar Banga Krishi Viswavidyalaya",
    "Uttar Pradesh University of Medical Sciences",
    "Uttarakhand Sanskrit University",
    "Uttarakhand Technical University",
    "Vardhman Mahaveer Open University",
    "Veer Bahadur Singh Purvanchal University",
    "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture and Forestry",
    "Veer Kunwar Singh University",
    "Veer Narmad South Gujarat University",
    "Veer Surendra Sai University of Technology",
    "Vellore Institute of Technology",
    "Vidyasagar University",
    "Vikram University",
    "Vikram Simhapuri University",
    "Vinayaka Missions University",
    "Vinoba Bhave University",
    "Visva-Bharati University",
    "Visvesvaraya National Institute of Technology",
    "Visvesvaraya Technological University",
    "West Bengal State University",
    "West Bengal University of Animal and Fishery Sciences",
    "West Bengal University of Health Sciences",
    "West Bengal University of Technology",
    "Yashwantrao Chavan Maharashtra Open University",
    "Yenepoya University",
    "YMCA University of Science and Technology"
]
