
export const universities: string[] = [
    "Acharya N.G. Ranga Agricultural University",
    "Acharya Nagarjuna University",
    "Adikavi Nannaya University",
    "Andhra Kesari University",
    "Andhra University",
    "Bharatiya Engineering Science and Technology Innovation University",
    "Central University of Andhra Pradesh",
    "Central Tribal University of Andhra Pradesh",
    "Centurion University of Technology and Management",
    "Cluster University",
    "Damodaram Sanjivayya National Law University",
    "Dr. Abdul Haq Urdu University",
    "Dr. B.R. Ambedkar University",
    "Dravidian University",
    "Dr. Y.S.R Architecture and Fine Arts University",
    "Dr. Y.S.R. Horticultural University",
    "Dr. N.T.R. University of Health Sciences",
    "Gandhi Institute of Technology and Management (GITAM)",
    "Jawaharlal Nehru Technological University",
    "Jawaharlal Nehru Technological University - Gurajada",
    "Koneru Lakshmaiah Education Foundation",
    "KREA University",
    "Krishna University",
    "Rajiv Gandhi University of Knowledge Technologies Andhra Pradesh",
    "Rayalaseema University",
    "Saveetha Amaravati University",
    "Sri Krishnadevaraya University",
    "Sri Padmavati Mahila Vishwavidyalayam",
    "Sri Sathya Sai Institute of Higher Learning",
    "Sri Venkateswara University",
    "Sri Venkateswara Vedic University",
    "Sri Venkateswara Veterinary University",
    "Sri Venkateswara Institute of Medical Sciences",
    "SRM University",
    "The National Sanskrit University",
    "Vignan's Foundation for Science, Technology and Research",
    "Vikrama Simhapuri University",
    "VIT-AP University",
    "Yogi Vemana University",
    "Apex Professional University",
    "Arunachal University of Studies",
    "Arunachal Pradesh University",
    "Arunodaya University",
    "Himalayan University",
    "North East Frontier Technical University",
    "North Eastern Regional Institute of Science & Technology",
    "Rajiv Gandhi University",
    "The Global University",
    "The Indira Gandhi Technological & Medical Sciences University",
    "Venkateshwara Open University",
    "Assam Agricultural University",
    "Assam Don Bosco University",
    "Assam Down Town University",
    "Assam University",
    "Assam Rajiv Gandhi University of Co-operative Management",
    "Assam Science & Technology University",
    "Assam Women’s University",
    "Birangana Sati Sadhani Rajyik Vishwavidyalaya",
    "Bodoland University",
    "Bhattadev University",
    "Cotton Univeristy",
    "Central Institute of Technology (CIT)",
    "Dibrugarh University",
    "Gauhati University",
    "Girijananda Chowdhury University Assam",
    "Krishna Kanta Handiqui State Open University",
    "Kumar Bhaskar Varma Sanskrit & Ancient Studies University",
    "Krishnaguru Adhyatmik Visvavidyalaya",
    "Madhabdev University",
    "Mahapurusha Srimanta Sankaradeva Viswavidyalaya",
    "Majuli University of Culture",
    "National Law University and Judicial Academy",
    "Pragjyotishpur University",
    "Rabindranath Tagore University",
    "Srimanta Sankaradeva University of Health Sciences",
    "Sri Sri Anirudhadeva Sports University",
    "Tezpur University",
    "The Assam Kaziranga University",
    "The Assam Royal Global University",
    "Amity University",
    "Aryabhatta knowledge University",
    "Babasaheb Bhimrao Ambedkar Bihar University",
    "Bhupendra Narayan Mandal University",
    "Bihar Agricultural University",
    "Bihar Animal Sciences University",
    "Central University of South Bihar",
    "Chanakya National Law University",
    "Dr. C.V. Raman University",
    "Gopal Narayan Singh University",
    "Jai Prakash Vishwavidyalaya",
    "Kameshwara Singh Darbhanga Sanskrit Vishwavidyalaya",
    "K.K. University",
    "Lalit Narayan Mithila University",
    "Magadh University",
    "Mahatma Gandhi Central University",
    "Mata Gujri University",
    "Maulana Mazharul Haque Arabic & Persian University",
    "Munger University",
    "Nalanda University",
    "Nalanda Open University",
    "Nava Nalanda Mahavihara",
    "Patna University",
    "Patliputra University",
    "Purnea University",
    "Dr. Rajendra Prasad Central Agricultural University",
    "Sandip University",
    "T.M. University",
    "Veer Kunwar Singh University",
    "Al-Karim University",
    "AAFT University of Media and Arts",
    "Ayush and Health Sciences University of Chhattisgarh",
    "Bharti Vishwavidyalaya",
    "Atal Bihari Vajpayee Vishwavidyalaya",
    "Chhattisgarh Kamdhenu Vishwavidyalaya",
    "Chhattisgarh Swami Vivekanand Technical University",
    "Dev Sanskriti Vishwavidyalaya",
    "Durg Vishwavidyalaya",
    "Guru Ghasidas Vishwavidyalaya",
    "Hidayatullah National Law University",
    "ICFAI University",
    "International Institute of Information Technology",
    "ISBM University",
    "Indira Gandhi Krishi Vishwavidyalaya",
    "Indira Kala Sangeet Vishwavidyalaya",
    "ITM University",
    "K.K. Modi University",
    "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
    "Kalinga University",
    "Maharishi University of Management and Technology",
    "Mahatma Gandhi Udyanikee Evam Vanikee Vishwavidyalaya",
    "MATS University",
    "O.P. Jindal University",
    "Pt. Ravishankar Shukla University",
    "Pandit Sundar Lal Sharma (Open) University Chhatisgarh",
    "Sant Gahira Guru Vishwavidyalaya",
    "Shaheed Mahendra Karma Vishwavidyalaya",
    "Shaheed Nandkumar Patel Vishwavidyalaya",
    "Shri Rawatpura Sarkar University",
    "Shri Shankaracharaya Professional University",
    "Goa University",
    "India International University of Legal Education and Research",
    "Adani University",
    "Ahmedabad University",
    "Anand Agricultural Univerisity",
    "Anant National University",
    "Atmiya University",
    "AURO University of Hospitality and Management",
    "Bhagwan Mahavir University",
    "Bhaikaka University",
    "Bhakta Kavi Narsinh Mehta University",
    "Birsa Munda Tribal University",
    "Central University of Gujarat",
    "Gati Shakti Vishwavidyalaya",
    "Centre for Environmental Planning and Technology University",
    "Charotar University of Science & Technology",
    "Children’s University",
    "C.U. Shah University",
    "Darshan University",
    "Dharmsinh Desai University",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "Dr. Babasaheb Ambedkar Open University",
    "Drs. Kiran & Pallavi Patel Global University (KPGU)",
    "Dr. Subhash University",
    "Ganpat University",
    "G.L.S. University",
    "Gandhinagar University",
    "Gokul Global University",
    "GSFC University",
    "Gujarat Ayurveda University",
    "Gujarat Biotechnology University",
    "Gujarat Maritime University",
    "Gujarat National Law University",
    "Gujarat Natural Farming and Organic Agricultural University",
    "Gujarat Technlogical University",
    "Gujarat University",
    "Gujarat University of Transplantation Sciences",
    "Gujarat Vidyapith",
    "Hemchandracharya North Gujarat University",
    "Indian Institute of Public Health",
    "Indian Institute of Teacher Education",
    "Indrashil University",
    "Indus University",
    "Institute of Infrastructure Technology Research and Management",
    "Institute of Advanced Research",
    "ITM (SLS) Baroda University",
    "ITM-Vocational University",
    "J.G. University",
    "Junagarh Agricultural University",
    "Kadi Sarva Vishwavidyalaya",
    "Kamdhenu University",
    "Karnavati University",
    "Krantiguru Shyamji Krishna Verma Kachchh University",
    "“Kaushalya” the Skill University",
    "Lakulish Yoga University",
    "Lok Jagruti Kendra University",
    "Lokbharati University for Rural Innovation",
    "Maganbhai Adenwala Mahagujarat University",
    "Maharaja Krishnakumarsinji Bhavnagar University",
    "Maharaja Sayajirao University of Baroda",
    "Marwadi University",
    "Monark University",
    "National Rail and Transportation Institute (NRTI)",
    "Navsari Agricultural University",
    "Nirma University",
    "Navrachana University",
    "Noble University",
    "Pandit Deendayal Energy University",
    "Parul University",
    "Plastindia International University",
    "P.P. Savani University",
    "R.K. University",
    "Rai University",
    "Sabarmati University",
    "SKIPS University",
    "Sankalchand Patel University",
    "Sardar Krushinagar Dantiwada Agricultural University",
    "Sardar Patel University",
    "Sarvajanik University",
    "Saurashtra University",
    "Shree Somnath Sanskrit University",
    "Shreyarth University",
    "Shri Govind Guru University",
    "Silver Oak University",
    "Sumandeep Vidyapeeth",
    "Surendranagar University",
    "Swaminarayan University",
    "Swarnim Gujarat Sports University",
    "Swarnim Startup & Innovation University",
    "Team Lease Skills University",
    "The Charutar Vidya Mandal (CVM) University",
    "Transstadia University",
    "UKA Tarsadia University",
    "UPL University of Sustainable Technology",
    "Vanita Vishram Women’s University",
    "Veer Narmad South Gujarat University",
    "Vidhyadeep University",
    "Al-Falah University",
    "Apeejay Stya University",
    "Ashoka University",
    "Bhagat Phool Singh Mahila Vishwavidyalaya",
    "Baba Mast Nath University",
    "BML Munjal University",
    "Central University of Haryana",
    "Chaudhary Bansi Lal University",
    "Chaudhary Devi Lal University",
    "Chaudhary Ranbir Singh University",
    "Choudhary Charan Singh Haryana Agricultural University",
    "Deen Bandhu Chhotu Ram University of Science & Technology",
    "Dr. B.R. Ambedkar National Law University",
    "G.D. Goenka University",
    "Geeta University",
    "Guru Jambeshwar University of Science and Technology",
    "Gurugram University",
    "Shri Vishwakarma Skill University",
    "IILM University",
    "Indira Gandhi University",
    "Jagan Nath University",
    "J.C Bose University of Science & Technology",
    "K.R. Mangalam University",
    "Kurukshetra University",
    "Lingaya’s Vidyapeeth",
    "Lala Lajpat Rai University of Veterinary & Animal Sciences",
    "Maharana Pratap Horticultural University",
    "Maharishi Balmiki Sanskrit University",
    "Maharishi Dayanand University",
    "Maharishi Markandeshwar",
    "Manav Rachna International Institute of Research & Studies",
    "Manav Rachna University",
    "M.V.N. University",
    "National Brain Research Centre",
    "National Dairy Research Institute",
    "National Institute of Food Technology, Entrepreneurship & Management (NIFTEM)",
    "NIILM University",
    "Om Sterling Global University",
    "O.P. Jindal Global University",
    "PDM University",
    "Pt. Bhagwat Dayal Sharma University of Health Sciences",
    "Pandit Lakhmi Chand State University of Performing and Visual Arts",
    "Rishihood University",
    "Shree Guru Gobind Singh Tricentenary University",
    "Shri Krishna AYUSH University",
    "SRM University",
    "Starex University",
    "Sushant University",
    "The Northcap University",
    "World University of Design",
    "Abhilashi University",
    "ArniUniversity",
    "A.P.G. (Alakh Prakash Goyal) Shimla University",
    "Atal Medical and Research University",
    "Baddi University of Emerging Sciences & Technology",
    "Bahra University",
    "Career Point University",
    "Central University of Himachal Pradesh",
    "Chitkara University",
    "Dr. Y.S. Parmar University of Horticulture & Forestry",
    "Eternal University",
    "Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya",
    "Himachal Pradesh National Law University",
    "Himachal Pradesh University",
    "Himachal Pradesh Technical University",
    "I.E.C. (India Education Centre) University",
    "Indus International University",
    "Jaypee University of Information Technology",
    "Maharishi Markandeshwar University",
    "Maharaja Agrasen University",
    "Manav Bharti University",
    "Sardar Patel University Mandi",
    "Shoolini University of Biotechnology and Management Sciences",
    "Sri Sai University",
    "Baba Ghulam Shah Badshah University",
    "Central University of Kashmir",
    "Central University of Jammu",
    "Cluster University of Jammu",
    "Cluster University of Srinagar",
    "Islamic University of Science & Technology University",
    "Sher-e-Kashmir University of Agricultural Science & Technology",
    "Shri Mata Vaishno Devi University",
    "University of Jammu",
    "University of Kashmir",
    "AISECT University",
    "ARKA Jain University",
    "Binod Bihar Mahto Koylanchal University",
    "Birla Institute of Technology",
    "Birsa Agricultural University",
    "Capital University",
    "Central University of Jharkhand",
    "Dr. Shyama Prasad Mukherjee University",
    "Jharkhand Rai University",
    "Jharkhand Raksha Shakti University",
    "Jharkhand University of Technology",
    "Kolhan University",
    "Nilamber-Pitamber University",
    "National University of Study & Research in Law",
    "Netaji Subhas University",
    "Pragyan International University",
    "Radha Govind University",
    "Ram Krishana Dharmarth Foundation University",
    "Ramchandra Chandravansi University",
    "Ranchi University",
    "Sai Nath University",
    "Sarla Birla University",
    "Sido Kanhu Murmu University",
    "Srinath University",
    "The Institute of Chartered Financial Analysts of India University",
    "Usha Martin University",
    "Vinoba Bhave University",
    "YBN University",
    "Adichunchanagiri University",
    "Alliance University",
    "Atria University",
    "Azim Premji University",
    "B.L.D.E. Bijapur",
    "Bangalore University",
    "Bengaluru City University",
    "Bengaluru Dr. B.R. Ambedkar School of Economics University",
    "Bengaluru North University",
    "Central University of Karnataka",
    "Christ",
    "Chanakya University",
    "CMR University",
    "Davangere University",
    "Dayananda Sagar University",
    "Garden City University",
    "Gulbarga University",
    "Indian Institute of Science",
    "International Institute of Information Technology",
    "JSS Academy of Higher Education & Research",
    "Jain",
    "JSS Science & Technology University",
    "Jawaharlal Nehru Centre for Advanced Scientific Research",
    "Karnataka Janapada Vishwavidyalaya",
    "Kannada University",
    "Karnataka State Law University",
    "Karnataka State Open University",
    "Karnataka State Rural Developoment and Panchayat Raj University",
    "Karnataka State Women University",
    "Karnataka University",
    "Karnataka Veterinary, Animal & Fisheries Science University",
    "Karnataka Samskrit University",
    "Karnataka Folklore University",
    "Khaja Bandanawaz University",
    "KLE Academy of Higher Education and Research",
    "KLE Technological University",
    "KSGH Music and Performing Arts University",
    "Kuvempu University",
    "Maharani Cluster University",
    "Mandya University",
    "Mangalore University",
    "Manipal Academy of Higher Education",
    "M.S. Ramaiah University of Applied Sciences",
    "Nrupathunga University",
    "National law School of India University",
    "NITTE",
    "PES University",
    "Presidency University",
    "Rai Technology University",
    "Raichur University",
    "Rajiv Gandhi University of Health Sciences",
    "Rani Channamma University",
    "Reva University",
    "RV University",
    "Sharnbasva University",
    "Shri Dharmasthala Manjunatheshwara University",
    "Sri Devraj Urs Academy of Higher Education and Research",
    "Sri Sathya Sai University for Human Excellence",
    "Sri Jagadhguru Murugarajendra University",
    "Sri Siddhartha Academy of Higher Education",
    "Srinivas University",
    "Swami Vivekananda Yoga Anusandhana Sansthana",
    "St. Joseph’s University",
    "The University of Trans-Disciplinary Health Sciences and Technology",
    "Tumkur University",
    "University of Agricultural Sciences",
    "University of Horticultural Sciences",
    "University of Mysore",
    "Vidyashilp University",
    "Visveswaraiah Technological University",
    "Vijayanagara Sri Krishnadevaraya University",
    "Yenepoya",
    "A.P.J. Abdul Kalam Technological University",
    "Central University of Kerala",
    "Chinmaya Vishwavidyapeeth",
    "Cochin University of Science & Technology",
    "Indian Institute of Space Science and Technology",
    "Kannur University",
    "Kerala Agricultural University",
    "Kerala Kalamandalam",
    "Kerala University of Digital Sciences Innovation and Technology",
    "Kerala University of Fisheries & Ocean Studies",
    "Kerala University of Health Sciences",
    "Kerala Veterinary & Animal Sciences University",
    "Mahatma Gandhi University",
    "National University of Advanced Legal Studies (NUALS)",
    "Shree Sankaracharya University of Sanskrit",
    "Sreenarayanaguru Open University",
    "Thunchath Ezhuthachan Malayalam University",
    "University of Calicut",
    "University of Kerala",
    "A.K.S. University",
    "Atal Bihari Vajpai Hindi Vishwavidyalaya",
    "Avantika University",
    "Awadesh Pratap Singh University",
    "Barkatullah University",
    "Bhabha University",
    "Devi Ahilya Vishwavidyalaya",
    "Dharmashastra National Law University",
    "Dr. A.P.J. Abdul Kalam University",
    "Dr. B.R. Ambedkar University of Social Sciences",
    "Dr. Harisingh Gour Vishwavidyalaya",
    "Eklavya University",
    "G.H. Raisoni University",
    "I.E.S University",
    "Jagran Lakecity University",
    "Jawaharlal Nehru Krishi Vishwavidyalaya",
    "Jaypee University of Engineering & Technology",
    "Jiwaji University",
    "Lakshmibai National Institute of Physical Education",
    "LNCT University",
    "Madhya Pradesh Medical Science University",
    "Madhyanchal Professional University",
    "Mahakaushal University",
    "Maharaja Chhatrasal Bundelkhand Vishwavidyalaya",
    "Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya",
    "M.P.Bhoj (open) University",
    "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
    "Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya",
    "Makhanlal Chaturvedi National University of Journalism and Communication",
    "Malwanchal University",
    "Mandsaur University",
    "Mangalayatan University",
    "Mansarovar Global University",
    "Medi-Caps University",
    "Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya",
    "National Law Institute University",
    "Oriental University",
    "Pandit S.N. Shukla University",
    "People’s University",
    "P.K. University",
    "Raja Mansingh Tomar Music & Arts University",
    "Raja Shankar Shah University",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
    "Rani Durgavati Vishwavidyalaya",
    "RKDF University",
    "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
    "Rabindranath Tagore University",
    "Renaissance University",
    "Sage University",
    "Sanjeev Agrawal Global Educational University",
    "SAM Global University",
    "Sanchi University of Buddhist-Indic Studies",
    "Sardar Patel University",
    "Sarvepalli Radhakrishnan University",
    "Shri Krishna University",
    "Shri Vaishnav Vidyapeeth Vishwavidyalaya",
    "Sri Aurobindo University",
    "Sri Satya Sai University of Technology & Medical Sciences",
    "Swami Vivekanand University",
    "Symbiosis University of Applied Sciences",
    "Techno Global University",
    "The Indira Gandhi National Tribal University",
    "Vikram University",
    "Vikrant University",
    "VIT Bhopal University",
    "Ajeenkya D.Y. Patil University",
    "ATLAS SKILLTECH UNIVERSITY",
    "Bharati Vidyapeeth",
    "Central Institute of Fisheries Education",
    "Chhatrapati Shivaji Maharaj University",
    "Dr. Homi Bhabha State University",
    "D.Y. Patil Agriculture and Technical University",
    "D.Y. Patil Educational Society",
    "D.Y. Patil International University",
    "Datta Meghe Institute of Higher Education & Research",
    "Deccan College of Post-Graduate & Research Institute",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Dr. Babasaheb Ambedkar Technological University",
    "Dr. D.Y. Patil Vidyapeeth",
    "Dr. Punjabrao Deshmukh Krishi Vidyapeeth",
    "Dr. Vishwanath Karad MIT World Peace University",
    "Flame University",
    "Gokhale Institute of Politics & Economics",
    "Gondwana University",
    "Homi Bhabha National Institute",
    "Indira Gandhi Institute of Development Research",
    "Defence Institute of Advanced Technology",
    "Hyderabad (SIND) National Collegiate University",
    "Institute of Chemical Technology",
    "International Institute for Population Sciences",
    "International Sports Univeristy",
    "Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya",
    "Konkan Krishi Vidyapeeth",
    "Krishna Vishwa Vidyapeeth",
    "Maharashtra Animal & Fishery Sciences University",
    "Maharashtra Natinoal Law University",
    "Maharashtra University of Health Sciences",
    "Maharashtra State Skills University",
    "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalay",
    "Mahatma Phule Krishi Vidyapeeth",
    "Marathwada Agricultural University",
    "MGM Institute of Health Sciences",
    "MGM University",
    "MIT Art Design & Technology University",
    "Narsee Monjee Institute of Management Studies",
    "NICMAR University",
    "Kavayitri Bahinbai Chaudhari North Maharashtra University",
    "Padmashree Dr. D.Y. Patil Vidyapeeth",
    "Pravara Institute of Medical Sciences",
    "Sandip University",
    "Sanjay Ghodawat University",
    "Savitribai Phule Pune University",
    "Sant Gadge Baba Amravati University",
    "Shivaji University",
    "Smt. Nathibai Damodar Thackersey Women’s University",
    "Punyashlok Ahilyadevi Holkar Solapur University",
    "Somaiya Vidyavihar University",
    "Spicer Adventist University",
    "Sri Balaji University",
    "Swami Ramanand Teerth Marathwada University",
    "SYMBIOSIS International",
    "Symbiosis Skills and Professional University",
    "Tata Institute of Fundamental Research",
    "Tata Institute of Social Sciences",
    "The Rashtrasant Tukadoji Maharaj Nagpur University",
    "Tilak Maharashtra Vidyapeeth",
    "University of Mumbai",
    "Vijaybhoomi University",
    "Vishwakarma University",
    "Yashwant Rao Chavan Maharashtra Open University",
    "Asian International University",
    "Bir Tikendrajit University",
    "Central Agricultural University",
    "Dhanamanjuri University",
    "Khongnangthaba University",
    "Manipur International University",
    "Manipur University",
    "Manipur Technical University",
    "Manipur University of Culture",
    "National Sports University",
    "Sangai International University",
    "CMJ University",
    "Martin Luther Christian University",
    "Mahatma Gandhi University",
    "North East Adventist University",
    "North Eastern Hill University",
    "Techno Global University",
    "University of Science & Technology",
    "Maharashtra Institute of Technology University of Meghalaya",
    "William Carey University",
    "Mizoram University",
    "Nagaland University",
    "North East Christian University",
    "St. Joseph University",
    "The Global Open University",
    "AIPH University",
    "ASBM University",
    "Berhampur University",
    "Biju Patnaik University of Technology",
    "Birla Global University",
    "Central University of Odisha",
    "C.V. Raman Global University",
    "Fakir Mohan University",
    "Gandhi Institute of Engineering & Technology University",
    "Gangadhar Meher University",
    "Kalinga Institute of Industrial Technology",
    "Kalinga Institute of Social Sciences",
    "Khallikote University",
    "Kalahandi University",
    "Madhusudan Law University",
    "National law University",
    "Maharaja Sriram Chandra Bhanja Deo University",
    "Odisha State Open University",
    "Odisha University of Technology and Research",
    "Orissa University of Agriculture & Technology",
    "Rajendra University",
    "Rama Devi Women’s University",
    "Ravenshaw University",
    "Sambalpur University",
    "Shiksha ‘O’ Anusandhan",
    "Shri Jagannath Sanskrit Vishwavidyalaya",
    "Sri Sri University",
    "Utkal University",
    "Utkal University of Culture",
    "Veer Surendra Sai Institute of Medical Sciences and Research",
    "Veer Surendra Sai University of Technology",
    "XIM University",
    "Adesh University",
    "Akal University",
    "Baba Farid University of Health Sciences",
    "Central University of Punjab",
    "Chandigarh University",
    "C.T. University",
    "D.A.V. University",
    "Desh Bhagat University",
    "GNA University",
    "Guru Angad Dev Veterinary & Animal Sciences University",
    "Guru Kashi University",
    "Guru Nanak Dev University",
    "Guru Ravidas Ayurved University",
    "Jagat Guru Nanak Dev Punjab State Open University",
    "Lamrin Tech Skills University",
    "Lovely Professional University",
    "Maharaja Ranjit Singh Punjab Technical University",
    "Plaksha University Punjab",
    "Punjab Agricultural University",
    "Punjabi University",
    "Rayat Bahra University",
    "RIMT University",
    "Sant Baba Bhag Singh University",
    "Sant Longowal Institute of Engineering and Technology (SLIET)",
    "Sardar Beant Singh State University",
    "Shaheed Bhagat Singh State University",
    "Sri Guru Granth Sahib World University",
    "Sri Guru Ram Das University of Health Sciences",
    "Sri Guru Teg Bahadur State University of Law",
    "Thapar Institute of Engineering & Technology",
    "The I.K. Gujaral Punjab Technical University",
    "The Maharaja Bhupinder Singh Punjab Sports University",
    "The Rajiv Gandhi National University of Law",
    "Apex University",
    "Agriculture University",
    "Banasthali Vidyapith",
    "Bhagwant University",
    "Bhartiya Skill Development University",
    "Bhupal Nobles University",
    "Bikaner Technical University",
    "Birla Institute of Technology & Science",
    "Dr. Bhimrao Ambedkar Law University",
    "Dr. K.N. Modi University",
    "Geetanjali University",
    "Govind Guru Tribal University",
    "Haridev Joshi University of Journalism and Mass Communication",
    "HomoeopathyUniversity",
    "IIHMR University",
    "IIS",
    "Institute of Advanced Studies in Education",
    "Jagadguru Ramanandacharya Rajasthan Sanskrit University",
    "Jai Narain Vyas University",
    "Jain Vishva Bharati Institute",
    "Jaipur National University",
    "Janardan Rai Nagar Rajasthan Vidyapeeth",
    "Jodhpur National University",
    "Jayoti Vidyapeeth Women’s University",
    "J.K. Lakshmipat University",
    "J.E.C.R.C. University",
    "The LNM Institute of Information Technology",
    "Lords University",
    "Madhav University",
    "Maharaja Ganga Singh University",
    "Maharana Pratap University of Agriculture & Technology",
    "Maharishi Dayanand Saraswati University",
    "Mahatma Jyoti Rao Phule University",
    "Mahatma Gandhi University of Medical Sciences & Technology",
    "Maharaj Vinayak Global University",
    "Maharaja Surajmal Brij University",
    "Maharishi Arvind University",
    "Manipal University",
    "Maulana Azad University",
    "M.B.M. University",
    "Mewar University",
    "Mody University of Science and Technology",
    "Mohan Lal Sukhadia University",
    "National Institute of Ayurveda (NIA)",
    "National Law University",
    "Nims University Rajasthan",
    "NIIT University",
    "Nirwan University",
    "OPJS University",
    "Pacific Academy of Higher Education & Research University",
    "Pacific Medical University",
    "Pandit Deendayal Upadhyaya Shekhawati University",
    "Poornima University",
    "Pratap University",
    "Raffles University",
    "Rajasthan Agricultural University",
    "Rajasthan Ayurveda University",
    "Rajasthan Technical University",
    "Rajasthan University of Health Sciences",
    "Rajasthan University of Veterinary & Animal Sciences",
    "Rajasthan ILD Skills University (RISU)",
    "Raj Rishi Bhartrihari Matsya University",
    "R.N.B. Global University",
    "Sai Tirupati University",
    "Sangam University",
    "Sardar Patel University of Police, Security & Criminal Justice",
    "Shri Jagdish Prasad Jhabarmal Tibrewala University",
    "Shridhar University",
    "Shri Kallaji Vedic Vishvavidyalaya",
    "Shri Khushal Das University",
    "Shyam University",
    "Singhania University",
    "Sir Padmapat Singhania University",
    "Suresh Gyan Vihar University",
    "Sunrise University",
    "Tantia University",
    "University of Kota",
    "University of Engineering & Management",
    "University of Rajasthan",
    "University of Technology",
    "Vardhman Mahaveer Open University",
    "Vivekananda Global University",
    "Medhavi Skills University",
    "Sikkim Alpine University",
    "Sikkim International University",
    "Sikkim Manipal University",
    "Sikkim National Law University",
    "Sikkim Skill University",
    "Khangchendzonga State University",
    "Sikkim University",
    "Shri Ramasamy Memorial University",
    "Sikkim Professional University",
    "Academy of Maritime Education and Training",
    "Alagappa University",
    "Amrita Vishwa Vidyapeetham",
    "Anna University",
    "Annamalai University",
    "Avinashilingam Institute for Home Science & Higher Education for Women",
    "B.S. Abdur Rahman Crescent Institute of Science and Technology",
    "Bharath Institute of Higher Education & Research",
    "Bharathiar University",
    "Bharathidasan University",
    "Central University of Tamil Nadu",
    "Chennai Mathematical Institute",
    "Chettinad Academy of Research and Education (CARE)",
    "Dhanalakshmi Srinivasan University",
    "Dr. M.G.R. Educational and Research Institute",
    "Gandhigram Rural Institute",
    "Hindustan Institute of Technology and Science (HITS)",
    "Indian Maritime University",
    "Jeppiaar University",
    "Kalasalingam Academy of Research and Higher Education",
    "Karpagam Academy of Higher Education",
    "Karunya Institute of Technology and Sciences",
    "Madurai Kamraj University",
    "Manonmaniam Sundarnar University",
    "Meenakshi Academy of Higher Education and Research",
    "Mother Teresa Women’s University",
    "Noorul Islam Centre for Higher Education",
    "Periyar Maniammai Institute of Science & Technology (PMIST)",
    "Periyar University",
    "Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)",
    "Sai University",
    "S.R.M. Institute of Sciences and Technology",
    "Sathyabama Institute of Science and Technology",
    "Saveetha Institute of Medical and Technical Sciences",
    "Shanmugha Arts, Science, Technology and Research Academy (SASTRA)",
    "Shiv Nadar University",
    "Sri Chandrasekharandra Saraswati Vishwa Mahavidyalaya",
    "Sri Ramachandra Medical College and Research Institute",
    "St. Peter’s Institute of Higher Education and Research",
    "Tamil Nadu Teacher Education University",
    "Tamil University",
    "Tamilnadu Agricultural University",
    "Tamilnadu Dr. Ambedkar Law University",
    "Tamilnadu Dr. M.G.R. Medical University",
    "Tamilnadu Fisheries University",
    "Tamilnadu Music and Fine Arts University",
    "Tamilnadu National Law School",
    "Tamilnadu Open University",
    "Tamilnadu Physical Education and Sports University",
    "Tamilnadu Veterinary & Animal Sciences University",
    "Thiruvalluvar University",
    "University of Madras",
    "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology",
    "Vel’s Institute of Science, Technology & Advanced Studies (VISTAS)",
    "Vellore Institute of Technology",
    "Vinayaka Mission’s Research Foundation",
    "Anurag University",
    "Aurora Higher Education & Research Academy",
    "Chaitanya",
    "Dr. B.R. Ambedkar Open University",
    "ICFAI Foundation for Higher Education",
    "Jawaharlal Nehru Architecture and Fine Arts University",
    "Kakatiya University",
    "Kaloji Narayan Rao University of Health Sciences",
    "Mahindra University Bahadurpaly(V)",
    "Malla Reddy University",
    "Maulana Azad National Urdu University",
    "NALSAR University of Law",
    "Nizam’s Institute of Medical Sciences",
    "Osmania University",
    "PalamuruUniversity",
    "Potti Sreeramulu Telugu University",
    "Professor Jayashankar Telangana State Agricultural University",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Satavahana University",
    "Sri Konda Laxman Telangana State Horticultural University",
    "P.V. Narsimha Rao Telangana Veterinary University",
    "SR University",
    "Telangana University",
    "The English and Foreign Languages University",
    "University of Hyderabad",
    "Woxsen University",
    "Maharaja Bir Bikram University",
    "Tripura University",
    "Aligarh Muslim University",
    "Prof. Rajendra Singh (Rajju Bhaiya) University",
    "Atal Bihari Vajpayee Medical University",
    "Babasaheb Bhimrao Ambedkar University",
    "Banaras Hindu University",
    "Banda University of Agriculture & Technology",
    "Bareilly International University",
    "Bennett University",
    "Bhatkhande Music Institute",
    "Bundelkhand University",
    "Babu Banarasi Das University",
    "Central Institute of Higher Tibetan Studies",
    "Chandra Shekhar Azad University of Agriculture & Technology",
    "Chhatrapati Shahu Ji Maharaj University",
    "Choudhary Charan Singh University",
    "Dayalbagh Educational Institute",
    "Deen Dayal Upadhyay Gorakhpur University",
    "Dr. A.P.J. Abdul Kalam Technical University",
    "Dr Ram Manohar Lohia Awadh University",
    "Dr. Ram Manohar Lohia Institute of Medical Sciences",
    "Dr. B.R. Ambedkar University",
    "Dr. Ram Manohar Lohiya National Law University",
    "Dr. Shakuntala Misra National Rehabilitation University",
    "Era University",
    "F.S. University",
    "G.L.A. University",
    "Galgotias University",
    "Gautam Buddha University",
    "Harcourt Butler Technical University",
    "IIMT University",
    "IILM University",
    "Indian Veterinary Research Institute",
    "IFTM University",
    "Integral University",
    "Invertis University",
    "Jagadguru Rambhadracharya Divyang University",
    "Jannayak Chandrashekhar University",
    "Jaypee Institute of Information Technology",
    "Jaypee University",
    "J.S. University",
    "Khwaja Moinuddin Chishti Urdu, Arabi~Farsi University",
    "King George Medical University",
    "Madan Mohan Malviya University of Technology",
    "Maa Shakumbhari University",
    "Mahatma Jyotiba Phule Rohilkhand University",
    "Mahatma Gandhi Kashi Vidyapeeth",
    "Maharishi University of Information Technology",
    "Mahayogi Gorakhnath University Gorakhpur",
    "Mangalayatan University",
    "Mohammad Ali Jauhar University",
    "Monad University",
    "Narendra Deo University of Agriculture & Technology",
    "Nehru Gram Bharati",
    "Noida International University",
    "Raja Mahendra Pratap Singh State University",
    "Rajiv Gandhi National Aviation University",
    "Rama University",
    "Rani Lakshmi Bai Central Agricultural University",
    "Sam Higginbottom Institute of Agriculture, Technology & Sciences",
    "Sampurnanand Sanskrit Vishwavidyalaya",
    "Sanskriti University",
    "Santosh",
    "Sardar Vallabh Bhai Patel University of Agriculture & Technology",
    "Sharda University",
    "Shiv Nadar",
    "Shobhit Institute of Engineering & Technology",
    "Shobhit University",
    "Shri Ramswaroop Memorial University",
    "Siddharth University",
    "Swami Vivekanand Subharti University",
    "Shri Venkateshwara University",
    "Teerthanker Mahaveer University",
    "The Glocal University",
    "University of Lucknow",
    "United University",
    "U.P. King George’s University of Dental Science",
    "Uttar Pradesh Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidyalaya Evam Go-Anusandhan Sansthan",
    "U.P. Rajarshi Tandon Open University",
    "Uttar Pradesh University of Medical Sciences",
    "University of Allahabad",
    "Veer Bahadur Singh Purvanchal University",
    "Bhagwant Global University",
    "Dev Bhoomi Uttrakhand University",
    "Dev Sanskriti Vishwavidyalaya",
    "DIT University",
    "Doon University",
    "Forest Research Institute",
    "G.B. Pant University of Agriculture and Technology",
    "Graphic Era",
    "Graphic Era Hill University",
    "Gurukul Kangri Vishvidayala",
    "Hemvati Nandan Bahuguna Garhwal University",
    "Hemwati Nandan Bahuguna Medical Education University",
    "Himalayiya University",
    "Himgiri Zee University",
    "IMS Unison University",
    "Kumaun University",
    "Maharaja Agrasen Himalayan Garhwal University",
    "Motherhood University",
    "Quantum University",
    "Ras Bihari Bose Subharti University",
    "Sardar Bhagwan Singh University",
    "Shri Guru Ram Rai University",
    "Soban Singh Jeena University",
    "Sri Dev Suman Uttarakhand Vishwavidyalay",
    "Surajmal University",
    "Swami Rama Himalayan University",
    "University of Engineering and Technology Roorkee",
    "University of Patanjali",
    "University of Petroleum and Energy Studies",
    "Uttarakhand Ayurved University",
    "Uttarakhand Open University",
    "Uttarakhand Sanskrit University",
    "Uttrakhand Technical University",
    "Uttaranchal University",
    "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry",
    "Adamas University",
    "Alipurduar University",
    "Aliah University",
    "Bankura University",
    "Biswa Bangla Biswabidyalay",
    "Bidhan Chandra Krishi Vishwavidyalaya",
    "Brainware University",
    "Cooch Behar Panchanan Barma University",
    "Dakshin Dinajpur University",
    "Darjeeling Hills University",
    "Diamond Harbour Women’s University",
    "Harichand Guruchand University",
    "Hindi University",
    "Indian Association for the Cultivation of Science (IACS)",
    "Jadavpur University",
    "JIS University",
    "Kanyashree University",
    "Kazi Nazrul University",
    "Mahatma Gandhi University",
    "Maulana Abul Kalam Azad University of Technology",
    "Murshidabad University",
    "Netaji Subhash Open University",
    "Presidency University",
    "Rabindra Bharati University",
    "Raiganj University",
    "Ramakrishna Mission Vivekananda Educational and Research Institute",
    "Rani Rashmoni Green University",
    "Sadhu Ram Chand Murmu University of Jhargram",
    "Seacom Skills University",
    "Sidho-Kanho-Birsha University",
    "Sister Nivedita University",
    "St. Xavier’s University",
    "Swami Vivekananda University",
    "Techno India University",
    "The Neotia University",
    "The Sanskrit College and University",
    "The West Bengal National University of Juridical Science",
    "The West Bengal University of Health Sciences",
    "The West Bengal University of Teachers’ Training, Education Planning and Administration",
    "University of Burdwan",
    "University of Calcutta",
    "University of Engineering and Management",
    "University of Gour Banga",
    "University of Kalyani",
    "University of North Bengal",
    "Uttar Banga Krishi Vishwavidyalaya",
    "Vidyasagar University",
    "Vishwa Bharati University",
    "West Bengal State University",
    "West Bengal University of Animal and Fishery Sciences",
    "Dr. B.R. Ambedkar University",
    "Delhi Pharmaceutical Sciences & Research University",
    "Delhi Skill and Entrepreneurship University",
    "Delhi Sports University",
    "Delhi Teachers University",
    "Delhi Technological University",
    "Guru Gobind Singh Indraprastha Vishwavidyalaya",
    "Indian Agricultural Research Institute",
    "Indian Institute of Foreign Trade",
    "Indian Law Institute",
    "Indira Gandhi National Open University",
    "Indira Gandhi Delhi Technical University for Women",
    "Indraprastha Institute of Information Technology",
    "Institute of Liver and Biliary Sciences (ILBS)",
    "Jamia Hamdard",
    "Jamia Mallia Islamia University",
    "Jawaharlal Nehru University",
    "Morarji Desai National Institute of Yoga",
    "National Institute of Educational Planning and Administration",
    "National Law University",
    "National Museum Institute of History of Art, Conservation and Museology",
    "Netaji Subhas University of Technology",
    "Shri Lal Bahadur Shastri National Sanskrit University",
    "South Asian University",
    "The Central Sanskrit University",
    "TERI School of Advanced Studies",
    "University of Delhi",
    "Panjab University",
    "Punjab Engineering College",
    "Pondicherry University",
    "Puducherry Technological University",
    "Sri Balaji Vidyapeeth",
    "Central Institute of Buddhist Studies",
    "Sindhu Central University",
    "University of Ladakh"
]
